### ISSUE TITLE
Integration suddenly stopped  working

### ISSUE THREAD

**Issue by ghost** [Hyundai-Kia-Connect/kia_uvo#264]
This is what I get in the HA Log:
Updated HA and Integeration to tha latest version today.

This error originated from a custom integration.

Logger: custom_components.kia_uvo.Vehicle
Source: custom_components/kia_uvo/Vehicle.py:81
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 08:32:21 (1 occurrences)
Last logged: 08:32:21

kia_uvo - Exception in update : string indices must be integers - traceback: Traceback (most recent call last): File "/config/custom_components/kia_uvo/Vehicle.py", line 56, in update self.vehicle_data = await self.hass.async_add_executor_job( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/kia_uvo/KiaUvoApiEU.py", line 427, in get_cached_vehicle_status return response["resMsg"]["vehicleStatusInfo"] TypeError: string indices must be integers

**Comment by cdnninja** [comment]
Things to try: 

1. Confirm your kia/hyundai app is working and showing the car. 
2. Try an older version by using HACS to pick either the one you knew worked or atleast a few week old version. 
3. If that fails enable debug logging outlined on the main page of this repository and post the logs.

**Comment by fuatakgun** [comment]
@cdnninja , we should incorporate these steps into our readme file :-) they are just to the point

**Comment by Reidar6** [comment]
1: Working great
2: No differ even with really old version
3: Debug logging shown Errors like "Invalid request value - Invalid Application Id"
Deleted the Integration in HA, added it again and now it works. Strange but Im happy :)  

Thanks for a great integration!

**Comment by fuatakgun** [comment]
I feel like this will revive again :) lets see
