### ISSUE TITLE
carMessage / ttsMessage / activeDTC

### ISSUE THREAD

**Issue by Raptor607** [Hyundai-Kia-Connect/kia_uvo#269]
**Is your feature request related to a problem? Please describe.**
No problem - feature request. Requesting pull of additional data element

**Describe the solution you'd like**
Retrieve "carMessage" and/or "ttsMessage" from Kia response (at a minimum.)
 "dtcActiveCount", "dtcCategory", "dtcDetail", and other dtc fields (dtc = Diagnostic Trouble Code I'm guessing..) may also be of interest to some.
Desired in order to create alerts to devices including cell phone and TV to alert of issue not reported by driver...

**Include the logs of the end point from Data in HA if this is a sensor**
activeDTC":{"dtcActiveCount":"1","dtcCategory":[{"system":"2","systemName":"SAFETY","activeCount":1,"dtcDetail":[{"ecuId":"05A2","dtcCode":"B1493","dtcDate":{"utc":"20220126225041","offset":-5},"**carMessage**":"A possible condition with your Airbag??System has been detected. A full system check is recommended to be done soon. Please contact your local dealership to schedule an appointment.","webMessage":"&lt;strong&gt;Issue Description:&lt;/strong&gt;&lt;br /&gt;A possible condition with your Airbag??System has been detected.&lt;br /&gt;&lt;br /&gt;&lt;strong&gt;Recommendation:&lt;/strong&gt;&lt;br /&gt; A full system check is recommended to be done soon. Please contact your local dealership to schedule an appointment.&lt;br /&gt;","**ttsMessage**":"A possible condition with your Airbag??System has been detected. A full system check is recommended to be done soon. Please contact your local dealership to schedule an appointment.","systemName":"SAFETY","subSystemName":"Airbag","dtcPriority":"2A","image":{"imageName":"pc_06_airbag_warning_light.png","imagePath":"/content/dam/kia/us/owners/image/feature/maintenance/MIL","imageType":"2"}}]}],

**Describe alternatives you've considered**
No alternative - information not currently exposed as attributes to data entity

**Additional context**
Kia app displays "1 issue found".  Also displays "B1493 Warning" under "Diagnostic Issues".  Clicking this displays full message shown in log snip.  2020 US Kia Telluride

**Comment by cdnninja** [comment]
How do you want this displayed in home assistant?   Would just a count of DTCs be enough or are you looking for the details in some fashion?  I am trying to figure out how to not clutter the interface but also provide you the detail you need.   Maybe a count with the attributes being the details?

**Comment by Raptor607** [comment]
I think that would work well!

**Comment by cdnninja** [comment]
Sounds good.  I will create something for you to test.  Since I don't have a DTC on my car right now hard to test it.

**Comment by cdnninja** [comment]
DTC count will now show in the latest release.   If you update from master it will also have attributes that are the above raw json.  Not ideal but should let you know the code and description. 

Can you test and post a screenshot if you have a DTC?  If not I will close for now. We can adjust as others have DTCs.

**Comment by Raptor607** [comment]
This looks perfect!  Still having issues with calling service for start_climate and will submit a new issue soon.
