### ISSUE TITLE
Steering Wheel Heater shows wrong state

### ISSUE THREAD

**Issue by LuckyTriple7** [Hyundai-Kia-Connect/kia_uvo#291]
**Region and Brand of car**
Europe/Germany/Kia E NIRO

**Describe the bug**
Steering Wheel Heater shows always on, but the car is in the carport.
Atrributes DATA shows the following:

`    ign3: true
    hoodOpen: false
    transCond: true
    steerWheelHeat: 2
    sideBackWindowHeat: 0`

KIA Connect App show the correct state (off)

I don't think it's possible for the steering wheel heater to be on when the engine is off.

[enirodata.txt](https://github.com/fuatakgun/kia_uvo/files/8029726/enirodata.txt)

**Comment by povlhp** [comment]
It can, I can set my car to control steering wheel heater either automatically as part of climate, or demand it on. Climate is controlled without engine on EV cars.

**Comment by LuckyTriple7** [comment]
> We found this for seats that we assume wrong for some cars that 0 is off 1 is on. Turns out some have multiple settings.
> 
> Most likely this is similar. My current guess:
> 
> 0: off (legacy cars) 1: One (legacy cars) 2: On (new cars)
> 
> I am sure additional values exist on your car. Could you turn it on - rescan and see what number it reports? Play with settings as well. Someone reported here that this value may relate to other items: #279 this is however on the "start" climate instead of the viewing aspect. I would hope they align...
> 
> Here is what we found on seats recently: [#195 (comment)](https://github.com/fuatakgun/kia_uvo/issues/195#issuecomment-1008502684)

Hello, sounds good. i do this today, thx in advance.

**Comment by LuckyTriple7** [comment]
I switched on the steering wheel heating, the following value can then be seen:

_'steerWheelHeat': 1_

When the steering wheel heater is **off**, the value is

_'steerWheelHeat': 0_ (when the Car is charging) _'batteryCharge': True_
**or**
_'steerWheelHeat': 2  (when the Car is not charging) _batteryCharge': False_

**Comment by bkonings** [comment]
Not that it bothers me much, seems for my car the wheel heater is reported as off, it however does not have a wheel heater.
I would put it in the new cars category ;)

**Comment by cdnninja** [comment]
> Not that it bothers me much, seems for my car the wheel heater is reported as off, it however does not have a wheel heater. I would put it in the new cars category ;)

Yes this has been a struggle.  Finding new and old cars report very different data and we don't know what model, region brand or year should have what.  So if the data exists we show the sensor.  This works 90% of the time.

**Comment by povlhp** [comment]
The integration is not showing the sensor. It makes the sensor available. 
Interpretation and usage of the sensor is the task of the user. Except in the cases where there is no doubt.

**Comment by LuckyTriple7** [comment]
> The integration is not showing the sensor. It makes the sensor available. Interpretation and usage of the sensor is the task of the user. Except in the cases where there is no doubt.

A binary sensor only has the status on and off, I don't know how you can interpret something here yourself.

**Comment by cdnninja** [comment]
We will need to switch this from a binary sensor to a generic one with mapping.

**Comment by LuckyTriple7** [comment]
tested with 2.46, works now. Thx
