### ISSUE TITLE
Language of notifications in Bluelink app changed

### ISSUE THREAD

**Issue by sterhoke** [Hyundai-Kia-Connect/kia_uvo#339]
Car:
Hyundai Tucson PHEV

**Describe the bug**

The Integration is somehow changing the notification language in the Bluelink app.

We have the app in German and after adding the integration to HA we noticed that the language of the notifications from the Bluelink app (e.g. Car not locked, etc....) switched from German to English. Most likely it changes the complete app to English but this could be delayed as it seems to cache quite a lot. The notifications are just the first sign.

I tested the integration with my account and it changed over to English a while ago. I thought it was maybe a bug in the App but my dad told me after I switched the account in the integration over to his user (It is his car, not mine :) ) he noticed the English notifications but told me the app is still in German.

I Had to change to his account because the car constantly switched to my drivers profile and I figured it is because of the Integration which constantly pulled my profile.... My dad drives the car mainly so it was quite annoying for him to have my profile constantly selected in the car....

**To Reproduce**

Set up the integration

**Expected behavior**
Language in Bluelink app stays in German

**Comment by fuatakgun** [comment]
Can you try with a secondary account and report back if it is impacting main account?

**Comment by cdnninja** [comment]
#521  The underlying API has been updated to support this.   Just need to finish the home assistant work and test.

**Comment by cdnninja** [comment]
Please test under the "master" branch.  As of this weekend it will also be in the next release.

**Comment by cdnninja** [comment]
@thomastitze Is this something you could test out for me to make sure now resolved?
