### ISSUE TITLE
Allow disabling vehicles in 2.0.xx

### ISSUE THREAD

**Issue by yombo** [Hyundai-Kia-Connect/kia_uvo#466]
Using version 2.0.39
**Is your feature request related to a problem? Please describe.**
I only want to poll data for one car, even though there are 2 cars on my account.

The other KIA integration pulls more data attributes, which I enjoy for the EV6 with active UVO plan. However, for our Telluride with an expired UVO Plan, this integration seems to get data where the other integration does.

Basically, I use the other KIA integration for EV6, but this integration for Telluride. The other integration allows for disabling vehicles, while this integration doesn't.

**Describe the solution you'd like**
Allow a vehicle to be disabled/enabled.

**Describe alternatives you've considered**
I've looked around around on how to disable, but i can't seem to find a way.

**Comment by cdnninja** [comment]
Currently that isn't a feature.  I don't think it is high priority at the moment.   Can I ask what sensors you would like added?   As well can I confirm you are USA Kia?

**Comment by cdnninja** [comment]
Thinking more on it. Can you just disable in home assistant the device?

**Comment by cdnninja** [comment]
@yombo wanted to follow up on the above?
