### ISSUE TITLE
Failed to parse driving info error

### ISSUE THREAD

**Issue by aferrato** [Hyundai-Kia-Connect/kia_uvo#472]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe - Hyundai Kona HEV

**Version of the integration**
2.0.40

**Describe the bug**
In the logs I've found this error: Failed to parse driving info

**Debug logs if an error occurred**

> 2022-12-05 08:27:14.917 ERROR (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiEU] Failed to parse driving info. Possible reasons:
                                - incompatible vehicle (ICE?)
                                - new API format
                                - API outage
     
> Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 225, in update_vehicle_with_cached_state
    state = self._get_driving_info(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 566, in _get_driving_info
    drivingInfo = responseAlltime["resMsg"]["drivingInfoDetail"][0]
IndexError: list index out of range

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**
Force update

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fuatakgun** [comment]
As far as i can tell, this us expected (some car types do not produce this data) we just need to differentiate what is error and what is expected.

**Comment by aferrato** [comment]
ok, thank you.
how can I see a complete response from the API to understand what is supported and what is not?

**Comment by cdnninja** [comment]
Debug logging can be enabled by following the bottom of this page: https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/v2.0/README.md it will tell us what the response was from the API.   If your car doesn't support this I do think we will need to adjust our code to handle this better.

Do your entities work just an error in the logs?

**Comment by fuatakgun** [comment]
There might be different responses from driving info API.

```
[hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_driving_info response30d {'retCode': 'S', 'resCode': '0000', 'resMsg': {'drivingInfo': [{'drivingPeriod': 0}, {'drivingPeriod': 1}, {'drivingPeriod': 2}], 'drivingInfoDetail': []}, 'msgId': 'aa052e08-223e-42ba-a803-2ad6c776da0e'}
```

**Comment by aferrato** [comment]
@fuatakgun I've the same responses:
```
[hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_driving_info response30d 
{'retCode': 'S', 'resCode': '0000', 'resMsg': 
{'drivingInfo': [{'drivingPeriod': 0}, {'drivingPeriod': 1}
, {'drivingPeriod': 2}], 'drivingInfoDetail': []}, 
'msgId': '532b51dd-fb2b-4a2e-96af-aa75dc8abdd2'}
```

and this are the other info:
`[hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_cached_vehicle_status response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo': {'vehicleLocation': {'coord': {'lat': 43.72545, 'lon': 10.402467, 'alt': 0, 'type': 0}, 'head': 0, 'speed': {'value': 0, 'unit': 0}, 'accuracy': {'hdop': 0, 'pdop': 0}, 'time': '20221206064221'}, 'vehicleStatus': {'airCtrlOn': True, 'engine': True, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTemp': {'value': '0CH', 'unit': 0, 'hvacTempType': 1}, 'defrost': False, 'lowFuelLight': False, 'acc': True, 'hoodOpen': False, 'transCond': False, 'steerWheelHeat': 0, 'sideBackWindowHeat': 1, 'dte': {'value': 503, 'unit': 1}, 'tirePressureLamp': {'tirePressureLampAll': 0, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 97, 'batState': 0}, 'breakOilStatus': False, 'sleepModeCheck': False, 'time': '20221206070710', 'remoteWaitingTimeAlert': {'remoteControlAvailable': 1, 'remoteControlWaitingTime': 168, 'elapsedTime': '00:00:00'}, 'systemCutOffAlert': 0, 'tailLampStatus': 0, 'hazardStatus': 0}, 'odometer': {'value': 264.5, 'unit': 1}}}, 'msgId': '6203f9a8-24a8-43ce-99d0-07d1bf22e1c9'}`

no way to get EV Range or Total Range, right? (even though total range is in the bluelink app)

**Comment by cdnninja** [comment]
Latest version should fix this.  Please let me know if this isn't the case as I can't test it.

**Comment by aferrato** [comment]
> Latest version should fix this. Please let me know if this isn't the case as I can't test it.

no errors so far, thanks!
