### ISSUE TITLE
Miles Vs KM

### ISSUE THREAD

**Issue by mtsaair** [Hyundai-Kia-Connect/kia_uvo#473]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

UK Kia Niro PHEV 2020 Model

Version 1.8.5

I've set my "Kia Connect" app to be specified in Miles, my Car Dash is displaying in miles. However i'm noticing some issues. 

For example the Kia Connect app will display "remaining" distances as KM e.g. 566km, but the Car will be saying 566mi 

If i leave the integration setup as "km" the remaining distance is accurate (albeit the wrong uom) but the odometer will be off by a factor of 1.60934 changing it to "mi" in the config will cause the remaining distance to be off by a factor of 1.60934

Its like these numbers are somehow coming through with a different unit of measure on each? 

See images below (ill add a dash photo in a bit but my wife confirmed that the odo reading is 28375.5 mi, and the "remaining" is around 552 and the app also shows this (albeit as 552km) 

But as you can see in the screenshots from the integration

![image](https://user-images.githubusercontent.com/67500279/205659714-ab4affed-eff6-47bc-8373-245141545d97.png)

**Comment by mtsaair** [comment]
![image](https://user-images.githubusercontent.com/67500279/205693959-6ee96bcb-b506-4920-ab38-9dcff9693262.png)
Dashboard image to confirm

as you can see, the ODO reading is fine, but the Range Total, EV, Fuel are all skewed by the conversion factor? its almost like the Kia Connect app is not supplying the information in the setting it says which is again confirmed by these 2 screenshots from the kia connect app

**Comment by mtsaair** [comment]
![Screenshot_20221205-164744](https://user-images.githubusercontent.com/67500279/205694670-759a37aa-c9fb-424f-86f2-9e89d538ef50.png)
![Screenshot_20221205-164752](https://user-images.githubusercontent.com/67500279/205694692-0093ada8-df36-4d95-983f-a6ec5660b49d.png)

**Comment by cdnninja** [comment]
Thanks for sharing.  Could you try out the beta branch of 2.X to see if you have the same issue?  This can be done in HACS by enabling beta releases.  

Essentially how this works is:

1. Car has a unit set.  This dictates what unit the API returns.  It does tell us the unit in most cases. 
2. The app has a setting to convert to a different unit.  Based on above that doesn't actually work.
3. Home assistant has a global settings for unit.  That should convert what returns from the API to the unit set in the HA interface.
4. Old version 1.8.X had an override for home assistant units since the UK seems to like run in Miles yet still use Celsius for temp. This hasn't been implement yet and I am not sure if truly needed as this is a "global" home assistant issue for the UK.

**Comment by cdnninja** [comment]
As another note in either 1.8 or 2.X enable debug mode and post the cached vehicle data after removing sensitive data.   I am wondering if the API is responding with the wrong unit.  Can be done by following the bottom of this: https://github.com/Hyundai-Kia-Connect/kia_uvo/tree/v2.0

**Comment by mtsaair** [comment]
So moving to 2.0.40 has as you say removed the override for UOM 

Also appears to have changed a few sensor names? and now i get no EV battery status? 

![image](https://user-images.githubusercontent.com/67500279/205877534-04c96af3-cc87-415f-8101-fc0a252b272a.png)

I added the sections to the config yaml to get the logs, but cant see which you require? looking in full logs i dont see much, but i do see this? 

```Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: /usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py:230
First occurred: 09:43:56 (2 occurrences)
Last logged: 09:43:56

Failed to parse driving info. Possible reasons: - incompatible vehicle (ICE?) - new API format - API outage
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 225, in update_vehicle_with_cached_state
    state = self._get_driving_info(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 566, in _get_driving_info
    drivingInfo = responseAlltime["resMsg"]["drivingInfoDetail"][0]
IndexError: list index out of range
```

```
2022-12-06 09:43:56.123 ERROR (SyncWorker_9) [hyundai_kia_connect_api.KiaUvoApiEU] Failed to parse driving info. Possible reasons:
- incompatible vehicle (ICE?)
- new API format
- API outage
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 225, in update_vehicle_with_cached_state
state = self._get_driving_info(token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 566, in _get_driving_info
drivingInfo = responseAlltime["resMsg"]["drivingInfoDetail"][0]
IndexError: list index out of range
```

**Comment by mtsaair** [comment]
Does seem however all of the Unit_of_measurements are coming in as KM 

Seems possible that its a "unique" issue as you mention with the UK

![image](https://user-images.githubusercontent.com/67500279/205887517-19349008-7b44-4ea7-a8ee-bf625039b566.png)

But as you can see here - the "ranges" are all right, 25 is the right number as reported by the dash, but the UOM is incorrect
But the ODO reading is both displaying the incorrect UOM, and has multipled the correct number. 

You need to see the data you get from the cache i guess, but i cant see where to recover this?

**Comment by cdnninja** [comment]
Once you have added the debug lines and restarted it will show up in settings>system>logs scroll down and click load full logs.  You are looking for a line that says "get_cached_vehilce_status".

For the ones with the wrong units it seems that matches the mobile app? If so open a ticket with Kia as this seems to be a bug on that side.  We take that same data and trust it is correct for units reported.

What is incorrect in the Odometer? Your car reports 28000miles on the dash and is being converted correctly.  This is based on your home assistant settings.  Or are you saying you want it to show in miles when home assistant is set in metric?

**Comment by mtsaair** [comment]
> Once you have added the debug lines and restarted it will show up in settings>system>logs scroll down and click load full logs. You are looking for a line that says "get_cached_vehilce_status".
> 

There is nothing like this within my logs.

> For the ones with the wrong units it seems that matches the mobile app? If so open a ticket with Kia as this seems to be a bug on that side. We take that same data and trust it is correct for units reported.
> 

Yeah ill have to get onto them about this, doubt they will fix it but worth a try

> What is incorrect in the Odometer? Your car reports 28000miles on the dash and is being converted correctly. This is based on your home assistant settings. Or are you saying you want it to show in miles when home assistant is set in metric?

I think perhaps this will fix when the issues with the app are maybe fixed?

**Comment by cdnninja** [comment]
If your logs don't exist please confirm you have both Kia UVO and the api line set to debug. 

As well what is wrong with odometer? What is the home assistant setting set to for units?  The math looks correct and showing the matching unit to the math.

**Comment by cdnninja** [comment]
Next release you will be able to set the km/miles but it is per entity.

**Comment by cdnninja** [comment]
Your unit can now be set on the entity in the latest release. Closing this out as the other issue looks to be with the kia hyundai API.
