### ISSUE TITLE
Total Range sensor not created

### ISSUE THREAD

**Issue by aferrato** [Hyundai-Kia-Connect/kia_uvo#475]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**Region and Brand of car**
Europe - Hyundai Kona HEV

**Version of the integration**
2.0.40

**Describe the bug**
I can't get a sensor for the EV Range o the Total Range even though total range is in the bluelink app.
maybe because the vehicle type is HV and not HEV as you can see in the log below.

**Debug logs if an error occurred**
`[hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Vehicles Response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicles': [{'vin': 'XXXXX', 'vehicleId': 'XXXXX', 'vehicleName': 'KONA', 'type': 'HV', 'nickname': 'KONA', 'master': True, 'carShare': 1, 'regDate': '2022-12-02 19:21:05.307', 'detailInfo': {'inColor': 'TRY', 'outColor': 'R3G', 'saleCarmdlCd': 'CZ', 'bodyType': '2', 'saleCarmdlEnNm': 'KONA'}}]}, 'msgId': 'aa985f23-2ade-4c91-98f3-1ded14bf24a4'}
`
Other response with dte info:
`[hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_cached_vehicle_status response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo': {'vehicleLocation': {'coord': {'lat': XX, 'lon': XX, 'alt': 0, 'type': 0}, 'head': 0, 'speed': {'value': 0, 'unit': 0}, 'accuracy': {'hdop': 0, 'pdop': 0}, 'time': '20221206064221'}, 'vehicleStatus': {'airCtrlOn': True, 'engine': True, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTemp': {'value': '0CH', 'unit': 0, 'hvacTempType': 1}, 'defrost': False, 'lowFuelLight': False, 'acc': True, 'hoodOpen': False, 'transCond': False, 'steerWheelHeat': 0, 'sideBackWindowHeat': 1, 'dte': {'value': 503, 'unit': 1}, 'tirePressureLamp': {'tirePressureLampAll': 0, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 97, 'batState': 0}, 'breakOilStatus': False, 'sleepModeCheck': False, 'time': '20221206070710', 'remoteWaitingTimeAlert': {'remoteControlAvailable': 1, 'remoteControlWaitingTime': 168, 'elapsedTime': '00:00:00'}, 'systemCutOffAlert': 0, 'tailLampStatus': 0, 'hazardStatus': 0}, 'odometer': {'value': 264.5, 'unit': 1}}}, 'msgId': '6203f9a8-24a8-43ce-99d0-07d1bf22e1c9'}`

**To Reproduce**

**Expected behavior**
Get Range sensor in home assistant

**Screenshots**

**Additional context**

**Comment by aferrato** [comment]
Hi, the sensor is still not present on v2.0.43
thank you.

**Comment by cdnninja** [comment]
Should be solved in the latest release.  It is out of beta as well.

**Comment by aferrato** [comment]
> Should be solved in the latest release. It is out of beta as well.

perfect!
