### ISSUE TITLE
Odometer shows 0 when Engine is off after Updating Navigation System to EU December Update

### ISSUE THREAD

**Issue by LuckyTriple7** [Hyundai-Kia-Connect/kia_uvo#477]
**Region and Brand of car**

EU / KIA Niro EV

**Version of the integration**

1.8.5

**Describe the bug**

Odometer shows always 0 when Engine is off.
When Engine is on, Odometer shows the correct Value.
After Engine is off, Odometer shows 0

![image](https://user-images.githubusercontent.com/60685158/206497573-2ee9b54c-28ca-4621-b6d0-73cc3796dc70.png)

https://update.kia.com/EU/E1/updateNoticeView/999

**Debug logs if an error occurred**

No Error in Log

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by LuckyTriple7** [comment]
Tomorrow :-) I updated to 2.0.42, no Integration is unavailable.
hyundai_kia_connect_api.exceptions.RateLimitingError: Exceeds number of requests - Exceeds Number of Requests.

**Comment by cdnninja** [comment]
Out of interest do you have an aggressive update cycle for force updates?

**Comment by LuckyTriple7** [comment]
Here is the Content of the DATA Sensor:

friendly_name: E-NIRO Data
vehicle_data: 
  head: 308
  speed:
    value: 0
    unit: 1
  accuracy:
    hdop: 0
    pdop: 0
  time: '20221209055942'
vehicleStatus:
  airCtrlOn: false
  engine: false
  doorLock: true
  doorOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  trunkOpen: false
  airTemp:
    value: 02H
    unit: 0
    hvacTempType: 1
  defrost: false
  acc: false
  evStatus:
    batteryCharge: false
    batteryStatus: 82
    batteryPlugin: 0
    remainTime2:
      etc1:
        value: 22
        unit: 1
      etc2:
        value: 450
        unit: 1
      etc3:
        value: 125
        unit: 1
      atc:
        value: 125
        unit: 1
    drvDistance:
      - rangeByFuel:
          evModeRange:
            value: 382
            unit: 1
          totalAvailableRange:
            value: 382
            unit: 1
        type: 2
    reservChargeInfos:
      reservChargeInfo:
        reservChargeInfoDetail:
          reservInfo:
            day:
              - 5
            time:
              time: '0200'
              timeSection: 1
          reservChargeSet: false
          reservFatcSet:
            defrost: false
            airTemp:
              value: 0EH
              unit: 0
              hvacTempType: 1
            airCtrl: 0
            heating1: 0
      offpeakPowerInfo:
        offPeakPowerTime1:
          starttime:
            time: '0900'
            timeSection: 1
          endtime:
            time: '0600'
            timeSection: 0
        offPeakPowerFlag: 0
      reserveChargeInfo2:
        reservChargeInfoDetail:
          reservInfo:
            day:
              - 5
            time:
              time: '0530'
              timeSection: 0
          reservChargeSet: false
          reservFatcSet:
            defrost: false
            airTemp:
              value: 0EH
              unit: 0
              hvacTempType: 1
            airCtrl: 0
            heating1: 0
      reservFlag: 0
      ect:
        start:
          day: 9
          time:
            time: '1200'
            timeSection: 0
        end:
          day: 9
          time:
            time: '1200'
            timeSection: 0
      targetSOClist:
        - targetSOClevel: 80
          dte:
            rangeByFuel:
              evModeRange:
                value: 372
                unit: 1
              totalAvailableRange:
                value: 372
                unit: 1
            type: 2
          plugType: 0
        - targetSOClevel: 100
          dte:
            rangeByFuel:
              evModeRange:
                value: 477
                unit: 1
              totalAvailableRange:
                value: 477
                unit: 1
            type: 2
          plugType: 1
  ign3: true
  hoodOpen: false
  transCond: true
  steerWheelHeat: 2
  sideBackWindowHeat: 0
  tirePressureLamp:
    tirePressureLampAll: 0
    tirePressureLampFL: 0
    tirePressureLampFR: 0
    tirePressureLampRL: 0
    tirePressureLampRR: 0
  battery:
    batSoc: 74
    batState: 0
  sleepModeCheck: false
  time: '20221209065234'
  remoteWaitingTimeAlert:
    remoteControlAvailable: 1
    remoteControlWaitingTime: 168
    elapsedTime: '00:56:30'
  systemCutOffAlert: 0
  tailLampStatus: 0
  hazardStatus: 0
odometer:
  value: 0
  unit: 1
drvhistory:
  drivingPeriod: 1
  drivingDate: '202212'
  totalPwrCsp: 66024
  motorPwrCsp: 48289
  climatePwrCsp: 10044
  eDPwrCsp: 7120
  batteryMgPwrCsp: 0
  regenPwr: 27566
  calculativeOdo: 470
  consumption30d: 126

vehicle_name: E-NIRO

**Comment by cdnninja** [comment]
Does the native app work?

**Comment by cdnninja** [comment]
Sounds good.   I figured this was a kia/hyundai API bug.  One option if we hear of this being more widespread is us ignoring 0 values but rather not tinker with the data if only you.

**Comment by LuckyTriple7** [comment]
I solved it using a template and a utility meter. If the odometer is 0, the utility meter value is displayed. If the odometer value is correct, that value is used.

`     e_niro_odometer_filtered:
        friendly_name: "E-NIRO Odometer filtered"
        unit_of_measurement: km
        icon_template: "mdi:speedometer"
        value_template: >-
          {% if is_state('sensor.e_niro_odometer', '0') %}
            {{ states('sensor.kilometerzahler_e_niro_gesamt') }}
          {% else %}
            {{ states('sensor.e_niro_odometer') }}
            {% endif %}`

**Comment by heibatec** [comment]
Hi, I have the same issue, probably since the last hyundai car update.
I read in another forum that the wrong value is transmitted when the car is not running. Could you fix it so, that the odometer value is only valid when the car is running at the same time?

**Comment by JensKillermann** [comment]
> I solved it using a template and a utility meter. If the odometer is 0, the utility meter value is displayed. If the odometer value is correct, that value is used.
> 
> ` e_niro_odometer_filtered: friendly_name: "E-NIRO Odometer filtered" unit_of_measurement: km icon_template: "mdi:speedometer" value_template: >- {% if is_state('sensor.e_niro_odometer', '0') %} {{ states('sensor.kilometerzahler_e_niro_gesamt') }} {% else %} {{ states('sensor.e_niro_odometer') }} {% endif %}`

can you add your utility_meter setting? I think sensor.kilometerzahler_e_niro_gesamt is your utility meter.
