### ISSUE TITLE
Statistics missing for Car_Battery

### ISSUE THREAD

**Issue by hwitten** [Hyundai-Kia-Connect/kia_uvo#478]
Using Version 2.0.42
Statistics show for EV_Battery but it would be nice to also have it for the 12 Volt.

Link from Statistics Card:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by ParadingLunatic** [comment]
I actually came here to check on something like this.  I've got a Kia Stinger (in the US), and recently had info regarding the battery voltage, but it looks like the entity is now "unavailable".  The original entity was sensor.car_name_car_battery (for me it was sensor.my_stinger_car_battery).  I started monitoring this because it helps me determine if I've done a few too many short drives and need to take a longer drive to charge up the battery.

Out of the 25 entities I used to have, it's the only one now showing up as Unavailable.

**Comment by cdnninja** [comment]
> I actually came here to check on something like this.  I've got a Kia Stinger (in the US), and recently had info regarding the battery voltage, but it looks like the entity is now "unavailable".  The original entity was sensor.car_name_car_battery (for me it was sensor.my_stinger_car_battery).  I started monitoring this because it helps me determine if I've done a few too many short drives and need to take a longer drive to charge up the battery.
> 
> 
> 
> Out of the 25 entities I used to have, it's the only one now showing up as Unavailable.

Which version?

**Comment by ParadingLunatic** [comment]
> > I actually came here to check on something like this.  I've got a Kia Stinger (in the US), and recently had info regarding the battery voltage, but it looks like the entity is now "unavailable".  The original entity was sensor.car_name_car_battery (for me it was sensor.my_stinger_car_battery).  I started monitoring this because it helps me determine if I've done a few too many short drives and need to take a longer drive to charge up the battery.
> > Out of the 25 entities I used to have, it's the only one now showing up as Unavailable.
> 
> Which version?

Version 1.8.5.

Also currently my Kia Connect subscription is Ultimate (still my first free year).  It will be going down to the plus package when it comes time to renew.

**Comment by cdnninja** [comment]
Could you open a new issue and please enable debug logs and provide them?

**Comment by cdnninja** [comment]
@hwitten  this should be resolved in the latest.  Let me know if we can close it.

**Comment by hwitten** [comment]
All good in v2.0.43. Thank You!

**Comment by kunalkhosla** [comment]
@cdnninja , coming here from #493 . 
> this should be resolved in the latest

Is this for stinger or EV6? Or does it not matter? I still don't see it in 2.0.46 for EV6

**Comment by cdnninja** [comment]
Long term stats were solved for brand and regions that still have the 12v reported.
