### ISSUE TITLE
Control force update blackout by Home Assistant entity

### ISSUE THREAD

**Issue by WDrzewiecki** [Hyundai-Kia-Connect/kia_uvo#487]
Region: EU

It would be useful to be able to control force update by HA entity.
For example, when everyone is away from home, especially for a long time, there is no need to automatically force update the car's data.

**Comment by cdnninja** [comment]
Are you able to unpack your thoughts on this one?  Today a force update only occurs if more than XX minutes since last update.  So if the car is being driven and turned on and off it typically auto checks in which means a force update won't be called.

**Comment by WDrzewiecki** [comment]
In my case, I have a home assistant installed in my vacation home. During the winter, no one stays there, but the home assistant works all the time to manage the alarm and heating. So at a time when no one is there for such a long period of time it is pointless to update car's data if no one can see it anyway. On the other hand, turning the integration on and off every time is quite cumbersome. 

So the ability to block updates (forced as well as regular) for the time when no one is home would be convenient and would reduce unnecessary querying of the bluelink api.

**Comment by cdnninja** [comment]
I don't think you can automate config in HA. So even if I add a setting you won't be able to automate it.  I wouldn't want it as a switch on the car as most people wouldn't use it but would clutter the car interface.    Someone references a python script here that may do it for you? 

https://community.home-assistant.io/t/service-call-to-enable-disable-an-integration/485724

**Comment by WDrzewiecki** [comment]
Ok, thank you very much, I'll look at it
