### ISSUE TITLE
Problems with 2.46: All Services missing, Sensors Missing

### ISSUE THREAD

**Issue by LuckyTriple7** [Hyundai-Kia-Connect/kia_uvo#489]
**Region and Brand of car**

EU / KIA E NIRO

**Version of the integration**

2.46

**Describe the bug**

**All Services are not working after Updating to 2.46**

Logger: homeassistant.core
Source: core.py:1624
First occurred: 09:53:05 (11 occurrences)
Last logged: 09:53:05

Unable to remove unknown service kia_uvo/start_charge
Unable to remove unknown service kia_uvo/stop_charge
Unable to remove unknown service kia_uvo/set_charge_limits
Unable to remove unknown service kia_uvo/open_charge_port
Unable to remove unknown service kia_uvo/close_charge_port

**Sensors are missing after Update:**

sensor.e_niro_target_range_of_charce_dc
sensor.e_niro_target_range_of_charce_ac

**Comment by LuckyTriple7** [comment]
regarding the missing services:
Integration deleted, HA restarted. Added integration: services back.
Deleting without restarting HA does not help.
I have set the Geocoded Location option. Integration reloaded, the geocoded location sensor was then available, but the services were gone again.
After another HA restart, the services are now available again.

**Comment by micro521** [comment]
Now it looks good. 
What I did:
1. Geocoded location was switched on during upgrade of integration.
2. Services were missing.
3. Turned off Geocoded location.
4. Restarted HA.
5. Services came back.
6. Turned back on Geocoded locations.
7. Restarted HA.
8. Both services and geocoded location works.

**Comment by LuckyTriple7** [comment]
When reloading the integration, all services will be lost. I don't think it has anything to do with geocoded location.

**Comment by micro521** [comment]
You are right, I just tested it.
When I restart HA the services come back but when the integration is reloaded they are gone.

**Comment by fuatakgun** [comment]
We might need to move the call `async_setup_services` from `async_setup` to `async_setup_entry`.

This should add the services back after they are removed because of reloading.

**Comment by cdnninja** [comment]
Please retest on the latest build.

**Comment by micro521** [comment]
I have retested on the latest build.
I confirm the issue is fixed now.
Thanks for the quick actions.

**Comment by LuckyTriple7** [comment]
Good Morning, the Services Issue is fixed, but the target_range_of_charce_dc and target_range_of_charce_ac Sensors are still missing.

**Comment by cdnninja** [comment]
2.0.48 is released.  Please test it out.  Hoping it solves those sensors.

**Comment by LuckyTriple7** [comment]
Thx a lot, both Sensors are working now, great !

![image](https://user-images.githubusercontent.com/60685158/207937201-e3b0e506-55fa-4486-b71c-383a69ff34b4.png)

**Comment by cdnninja** [comment]
Great thanks for following up!
