### ISSUE TITLE
Charge door sensor shows open (regardless of actual status)

### ISSUE THREAD

**Issue by phantomsphorever** [Hyundai-Kia-Connect/kia_uvo#490]
Hyunday Ioniq 5 stationed in Switzerland

Integration version 2.0.46

The sensor for the charge door indicates open - regardless of the actual status of the charge door

**Expected behavior**
Sensor should follow actual status of door :-)

**Comment by cdnninja** [comment]
Are you able to enable debug logging and provide what the logs show?

**Comment by phantomsphorever** [comment]
I see what I can do tomorrow - I am currently banned because I had too many server requests :-(

**Comment by cdnninja** [comment]
Sounds good.  Searching through logs posted for other issues in the past it looks like I was wrong in my guess on chargePortDoorOpenStatus being a 0 or 1.  Looks like it is a 1 or 2 but I am not sure which means what.  If you could validate and compare it to the app when this is back up and working I can adjust our logic.

**Comment by phantomsphorever** [comment]
I just did a test and it seems that:

Open is "1"
Closed is "2"

**Comment by cdnninja** [comment]
Thank you for this.  I just merged a change into the API to follow this.   Next release should resolve.

**Comment by cdnninja** [comment]
2.0.48 is released.  Please test it out.

**Comment by phantomsphorever** [comment]
In 2.0.48 the sensor comes up as "unavailable"
I am still on HA 2022.12.5, but I guess that should not matter?

**Comment by cdnninja** [comment]
In HACS can you redownload from "master" and see if it works now?  And yes HA version shouldn't impact this.

**Comment by cdnninja** [comment]
2.0.49 is now out with this fix.

**Comment by phantomsphorever** [comment]
Works perfectly now!

Thank you very much - have a good weekend!
