### ISSUE TITLE
Kia EV6 - no remote climate option

### ISSUE THREAD

**Issue by andye2801** [Hyundai-Kia-Connect/kia_uvo#491]
Hi,

I'm running v2.0.46 and I understand that I should be able to start remote climate but I can't see that option.

Any logs or extra I can provide to look into this?

Andy

**Comment by phantomsphorever** [comment]
It is a service:
kia_uvo.start_climate
kia_uvo.stop_climate

**Comment by andye2801** [comment]
Ah my bad! Probably a case of RTFM! I'll take a look at the dev menu
