### ISSUE TITLE
Bring back the key fob battery warning sensor

### ISSUE THREAD

**Issue by phantomsphorever** [Hyundai-Kia-Connect/kia_uvo#496]
In the original version of the app, there was a sensor that told you if your key-fob battery had reached a critical stage.

**Describe the solution you'd like**
Bring back the sensor if possible.

**Include the logs of the end point from Data in HA if this is a sensor**
Amongst the data that is sent from the car when I do a forced update,  I found:
                                                     
                                                     ...................'smartKeyBatteryWarning': False............
                                                     
that data is just in front of the washer fluid data block (for that I did find the sensor in the current version ).
Not sure if the data is valid, but worth a try?

**Describe alternatives you've considered**
No alternatives - just a nice to have rather than going out to the car being told on the cars display that the key-fob battery is about to quit

Thanks for your consideration !

**Comment by cdnninja** [comment]
Which region and brand?

**Comment by phantomsphorever** [comment]
Sorry, this is for a Hyundai Ioniq 5 in Switzerland.

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/184 should resolve this in the next release.

**Comment by cdnninja** [comment]
2.0.48 is released.  Please test it out.

**Comment by phantomsphorever** [comment]
Sensor is back!


Great work - thanks a Million!

**Comment by cdnninja** [comment]
Glad to hear! Thanks for confirming.
