### ISSUE TITLE
binary_sensor.e_niro_data no longer available

### ISSUE THREAD

**Issue by felixnurse** [Hyundai-Kia-Connect/kia_uvo#499]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe Kia

**Version of the integration**
2.0.48

**Describe the bug**
Prior to the latest update, the integration returned a Data binary sensor entity. The attributes returned large amounts of data not returned in other entities (for example scheduled charging slots)

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.m

**To Reproduce**
Review entities and find no data entity

**Expected behavior**
A binary_sensor.e_niro_data entity is returned with attributes covering all data returned by the API

**Screenshots**

**Additional context**
I use the charging schedule attributes of the data sensor to determine when the car has "forgotten" my charging slot so I know to go and reset it.

Thank you!

**Comment by cdnninja** [comment]
If you update in HACS from "master" it should now be available.  It will be in the next release.

**Comment by cdnninja** [comment]
2.0.49 is now out with this fix.
