### ISSUE TITLE
Target Range Sensors unavailabe in 2.0.49

### ISSUE THREAD

**Issue by LuckyTriple7** [Hyundai-Kia-Connect/kia_uvo#505]
**Region and Brand of car**
EU / KIA E Niro

**Version of the integration**

2.0.49

**Describe the bug**

Following Sensors are unavailable in 2.0.49, in 2.0.48 OK

sensor.e_niro_target_range_of_charge_ac
sensor.e_niro_target_range_of_charge_dc

Data is existing in the new DATA Sensor. (Thx for bring back the DATA Sensor)

`vehicle_data: 
vehicleLocation:
  coord:
    lat: anonymized
    lon: anonymized
    alt: anonymized
    type: anonymized
  head: 220
  speed:
    value: 0
    unit: 1
  accuracy:
    hdop: 0
    pdop: 1
  time: '20221216083007'
vehicleStatus:
  airCtrlOn: false
  engine: false
  doorLock: true
  doorOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  trunkOpen: false
  airTemp:
    value: 02H
    unit: 0
    hvacTempType: 1
  defrost: false
  acc: false
  evStatus:
    batteryCharge: true
    batteryStatus: 58
    batteryPlugin: 2
    remainTime2:
      etc1:
        value: 37
        unit: 1
      etc2:
        value: 950
        unit: 1
      etc3:
        value: 230
        unit: 1
      atc:
        value: 195
        unit: 1
    drvDistance:
      - rangeByFuel:
          evModeRange:
            value: 271
            unit: 1
          totalAvailableRange:
            value: 271
            unit: 1
        type: 2
    reservChargeInfos:
      reservChargeInfo:
        reservChargeInfoDetail:
          reservInfo:
            day:
              - 5
            time:
              time: '0200'
              timeSection: 1
          reservChargeSet: false
          reservFatcSet:
            defrost: false
            airTemp:
              value: 0EH
              unit: 0
              hvacTempType: 1
            airCtrl: 0
            heating1: 0
      offpeakPowerInfo:
        offPeakPowerTime1:
          starttime:
            time: '0900'
            timeSection: 1
          endtime:
            time: '0600'
            timeSection: 0
        offPeakPowerFlag: 0
      reserveChargeInfo2:
        reservChargeInfoDetail:
          reservInfo:
            day:
              - 5
            time:
              time: '0530'
              timeSection: 0
          reservChargeSet: false
          reservFatcSet:
            defrost: false
            airTemp:
              value: 0EH
              unit: 0
              hvacTempType: 1
            airCtrl: 0
            heating1: 0
      reservFlag: 0
      ect:
        start:
          day: 9
          time:
            time: '1200'
            timeSection: 0
        end:
          day: 9
          time:
            time: '1200'
            timeSection: 0
      targetSOClist:
        - targetSOClevel: 80
          dte:
            rangeByFuel:
              evModeRange:
                value: 380
                unit: 1
              totalAvailableRange:
                value: 380
                unit: 1
            type: 2
          plugType: 0
        - targetSOClevel: 100
          dte:
            rangeByFuel:
              evModeRange:
                value: 488
                unit: 1
              totalAvailableRange:
                value: 488
                unit: 1
            type: 2
          plugType: 1
  ign3: true
  hoodOpen: false
  transCond: true
  steerWheelHeat: 0
  sideBackWindowHeat: 0
  tirePressureLamp:
    tirePressureLampAll: 0
    tirePressureLampFL: 0
    tirePressureLampFR: 0
    tirePressureLampRL: 0
    tirePressureLampRR: 0
  battery:
    batSoc: 73
    batState: 0
  sleepModeCheck: false
  time: '20221216083005'
  remoteWaitingTimeAlert:
    remoteControlAvailable: 1
    remoteControlWaitingTime: 168
    elapsedTime: '02:18:02'
  systemCutOffAlert: 0
  tailLampStatus: 0
  hazardStatus: 0
odometer:
  value: 0
  unit: 1

vehicle_name: E-NIRO
friendly_name: E-NIRO Data`

I have created a template which shows the values as two sensors..

`     e_niro_maxrange_ac_charging:
        friendly_name: 'Reichweite nach AC Ladung'
        value_template: "{{ state_attr('sensor.e_niro_data', 'vehicle_data')['vehicleStatus']['evStatus']['reservChargeInfos']['targetSOClist'][1]['dte']['rangeByFuel']['evModeRange']['value'] }}"
        unit_of_measurement: "km"
        icon_template: mdi:fuel-cell
     e_niro_maxrange_dc_charging:
        friendly_name: 'Reichweite nach DC Ladung'
        value_template: "{{ state_attr('sensor.e_niro_data', 'vehicle_data')['vehicleStatus']['evStatus']['reservChargeInfos']['targetSOClist'][0]['dte']['rangeByFuel']['evModeRange']['value'] }}"
        unit_of_measurement: "km"
        icon_template: mdi:fuel-cell`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Oops - looks like a fix was reverted.  2.0.50 will put that fix back.
