### ISSUE TITLE
Uprev manifest to 1.46

### ISSUE THREAD

**Issue by GD-L** [Hyundai-Kia-Connect/kia_uvo#506]
@cdnninja  - not sure if this is the correct reference point, but it should match the recent updates. 

https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/6ac2307145e4aebdc58a3a2a03b449d349a2b689/custom_components/kia_uvo/manifest.json#L7

**Comment by cdnninja** [comment]
Yes I intend to uplift this once someone has tested that 1.46 works. I can't test it since I don't have an EV where is the only code change in .46.

**Comment by GD-L** [comment]
Got it. It looked like 1.46 had the update to the locks, cause it's hasn't
come though kia_uvo yet.

**Comment by cdnninja** [comment]
Ahh right.  Yes it does.   Since your fix didn't have a semantic title it didn't get its own release.   If you want to test out you can manually set your manifest version to this version.   I am sure I'll release this soon.  I'm trying to bundle things more to release less often.

**Comment by GD-L** [comment]
I'll give that a try.  I have it working with the previous fix for now! You
can close this issue.
