### ISSUE TITLE
Start/stop charge failed silently 

### ISSUE THREAD

**Issue by adamchengtkc** [Hyundai-Kia-Connect/kia_uvo#509]
Debug in Hass enabled. Logging level debug

Start charge and end charge service call appear successful. No debug entry in the log. But no effect on the vehicle. This feature works previously on version 1.x

Start stop climate works

Hyundai Ioniq 5 EU

**Comment by adamchengtkc** [comment]
Running v2.0.50

**Comment by cdnninja** [comment]
One fix was put in since .50 for stop charge.  If you update from "master" you will receive that fix.   Sometimes the debug logs are delayed in showing up in hacs and need refresh.  I will review code to see if anything obvious stands out.

**Comment by adamchengtkc** [comment]
Confirmed .50 works.Thanks! Is it possible to update the charge status sensor after a successful service call? Instead of waiting another poll. Because in EU the API is rate limited
