### ISSUE TITLE
Lock sensor “UNLOCKED” only

### ISSUE THREAD

**Issue by CVHvisuals** [Hyundai-Kia-Connect/kia_uvo#510]
Lock sensor only show “unlocked” state. 
Latest beta release and all before. 

What happened? This used to work before 2.x
This is one of the most important sensors but no longer supported? US?

please revert to 1.x code of that is the case.

**Comment by cdnninja** [comment]
You can revert if you like.   I would rather fix it.  To confirm which version and what brand?

**Comment by cdnninja** [comment]
Could you try "master" and let me know it's the same?

**Comment by CVHvisuals** [comment]
The status now show “locked” for the sensor with the current master. 
I will follow up this evening with the results when I am near my vehicle. 
Thank you.

**Comment by cdnninja** [comment]
How did it test out that evening?

**Comment by CVHvisuals** [comment]
Traded it in. I no longer have this vehicle. Thank you for the support. On Dec 19, 2022, at 14:31, cdnninja ***@***.***> wrote:﻿
How did it test out that evening?
