### ISSUE TITLE
Missing Sensor: Set Temperature 

### ISSUE THREAD

**Issue by JosePeriban** [Hyundai-Kia-Connect/kia_uvo#515]
**Is your feature request related to a problem? Please describe.**
Not a problem 

**Describe the solution you'd like**

Bringing back the set temp sensor (without the HI or LO preferred) but either way is fine

**Include the logs of the end point from Data in HA if this is a sensor**

**Describe alternatives you've considered**

**Additional context**

**Comment by cdnninja** [comment]
Assuming from Kia USA could you update from "master" and let me know if fixed.  This was a large change for kia usa so it could cause the whole thing to break. I can't test as I don't have car in Kia USA region.

**Comment by cdnninja** [comment]
Please test the latest and let me know.  If it now a release as well.

**Comment by cdnninja** [comment]
@JosePeriban  any word if fixed?

**Comment by JosePeriban** [comment]
Tested latest v2.3.2 no temp sensor, still not resolved

**Comment by cdnninja** [comment]
Any errors in home assistant logs? 

Could I get the attributes of your data sensor?

**Comment by cdnninja** [comment]
Closing due to no reply.
