### ISSUE TITLE
Missing controls at Kia Seltos 2023

### ISSUE THREAD

**Issue by MrPresident2** [Hyundai-Kia-Connect/kia_uvo#517]
I'm missing most of the controls all I have is lock unlock, I'm missing engine start/stop and AC control. Anyone know how to solve it?

**Comment by cdnninja** [comment]
Please see the answer here: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/516

**Comment by cdnninja** [comment]
Closing as duplicate.
