### ISSUE TITLE
Odometer shows 0 after EU december car update

### ISSUE THREAD

**Issue by heibatec** [Hyundai-Kia-Connect/kia_uvo#518]
Hi, I have the same issue, probably since the last hyundai car update.
I read in another forum that the wrong value is transmitted when the car is not running. Could you fix it so, that the odometer value is only valid when the car is running at the same time?

_Originally posted by @heibatec in https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/477#issuecomment-1357497270_

**Comment by cdnninja** [comment]
Once you have a single scan that grabs a real value it will only use the ones when running so this is already done.  The odds you scan while running are slim though.  This isn't really fixable without hyundai solving it.

**Comment by cdnninja** [comment]
This is the current logic to try fix the issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/c3b9ab0cfad66ce5e44cfeb4413046cc694cf51e/hyundai_kia_connect_api/KiaUvoApiEU.py#L314-L324

**Comment by cdnninja** [comment]
If you prefer I can set it so it goes unavailable until a car running scan grabs a value.   That may be a long time though.

**Comment by heibatec** [comment]
I am not a coding guy, but I think this helps. Thank you.

**Comment by jjvandenberg** [comment]
Hi,
mine doesn't show zero (0,0) but an old ODO meter value from the past. i fixed it by adding an extra template var :

template:
  - sensor:
      - name: "kilometer_totaal"
        state: >
            {% if states.sensor.kilometer_totaal.state <  states.sensor.ev6_odometer.state %}
              {{ states.sensor.ev6_odometer.state | float }}
            {% endif %}
        state_class: total_increasing
        unit_of_measurement: km
        device_class: distance
        icon: mdi:speedometer

You can force un update from the couch by remote starting the car and after a few seconds pull an update.
This wil give you the currrent odo meter settings. then turn of the car with the remote.

**Comment by LuckyTriple7** [comment]
New KIA Update available, problem is fixed then for me:
Version: +|22Q2|DE_E_20.EUR.S5W_L.001.001.**221223**|KM|Niro_EV_MY_20_EU|1557|1

**Comment by beniwohli** [comment]
Same, the December update fixed it for my Hyundai.

**Comment by cdnninja** [comment]
Since they have a new update out for the cars I am going to go ahead and close this.   I also removed my defense code from the API as it didn't work well either.
