### ISSUE TITLE
device_id 

### ISSUE THREAD

**Issue by Desmo996** [Hyundai-Kia-Connect/kia_uvo#533]
I’m using node-red and since a recent update I now get “Call-service error. ‘device_id’” in my debug log and nothing is working. 

I have been given advice on how to fix this and now have my device_id which I have entered manually but could it be automatically used if there is just one car on the account?

**Comment by cdnninja** [comment]
Are you able to help me understand the challenge with telling home assistant which car to use?   I assume one you adjust your node red it will work permanently?  Are you already are passing other items to start_climate or other commands?  This item was added to support multiple cars.

**Comment by fuatakgun** [comment]
This was my idea, open to discussion, while entity id or VIN are predictable by user, device id is generated by home assistant.

if there is one car, can we fetch it automatically?

**Comment by cdnninja** [comment]
Would need to adjust this to have a way to confirm only a single coordinator exists and a single device in that coordinator: 

https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/9aab7beefb7893d42b724f5245d61ec8200bba8a/custom_components/kia_uvo/services.py#L141-L169

**Comment by hmorkemo** [comment]
> c

I have the same problem. What was the solution?

**Comment by fuatakgun** [comment]
https://community.home-assistant.io/t/kia-uvo-integration/297927/197

**Comment by hmorkemo** [comment]
> https://community.home-assistant.io/t/kia-uvo-integration/297927/197

Thank you! That did it. But this might just be the silliest breaking change I've seen in a Home Assistant integration. At least, it should be able to find the id itself in the most common case where there's only one car.

**Comment by cdnninja** [comment]
> > https://community.home-assistant.io/t/kia-uvo-integration/297927/197
> 
> 
> 
> Thank you! That did it. But this might just be the silliest breaking change I've seen in a Home Assistant integration. At least, it should be able to find the id itself in the most common case where there's only one car.

You are welcome to create a pull request with the resolution.

**Comment by cdnninja** [comment]
I had some time to figure this out tonight.   Re-download from HACS and select "master" as version.  Let me know if it solves your issues.
