### ISSUE TITLE
Entities become unavailable until reload, missing air conditioner binary_sensor, unknown state of locks

### ISSUE THREAD

**Issue by nprez83** [Hyundai-Kia-Connect/kia_uvo#534]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Kia Telluride 2020, US

**Version of the integration**
2.2.1

**Describe the bug**
There are three issues that all started together since upgrading to 2.2.1.
1) All entities become unavailable with the error on the log that I'm including below. If I reload the integration, the entities come back, but they go offline soon thereafter.
2) The binary_sensor.xxx_air_conditioner entity is no longer being provided by the integration so other than by looking at the raw data I have no way to know if the HVAC is on or not.
3) The state of the door locks is showing up as unknown, so the lock and unlock services are not working.

**Debug logs if an error occurred**
```
Logger: hyundai_kia_connect_api.KiaUvoAPIUSA
Source: /usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py:76
First occurred: 09:37:31 (2 occurrences)
Last logged: 09:37:32

hyundai_kia_connect_api - error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":1005,"errorMessage":"Invalid vehicle for current session"}}
```

**To Reproduce**
Add integration. You'll immediately notice the missing air_conditioner entity and the unknown state of the locks.
Give it some time and all entities will become unavailable, which can be fixed temporarily by reloading integration.

All is working well with the Kia app.

**Comment by cdnninja** [comment]
Any chance you loaded the mobile app in between?  

As for items missing could you post the attributes of your data sensor?

**Comment by cdnninja** [comment]
I believe this will solve the lock status: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/205

**Comment by nprez83** [comment]
Thanks for the quick turnaround. I see the changes you made are to the hyundai_kia_connect_api files, so I assume I have to change something in the requirements section of the manifest.json of the custom_component to get the updated code, do you know what that should be? Or should I wait for you to push a new version of the integration altogether?

**Comment by nprez83** [comment]
Ok, I changed the manifest to point it to api version 1.52.1, and the aircon and lock issue is indeed fixed. I'll give it some time and report on whether the issue with the entities becoming unavailable until reload is still present. That's as always.

**Comment by nprez83** [comment]
> Ok, I changed the manifest to point it to api version 1.52.1, and the aircon and lock issue is indeed fixed. I'll give it some time and report on whether the issue with the entities becoming unavailable until reload is still present. Thanks as always.

Ok, something is definitely still going on related to the connection. I just tried to run there update service and got the following two error messages.

```
Logger: hyundai_kia_connect_api.KiaUvoAPIUSA
Source: /usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py:76
First occurred: 12:41:32 (1 occurrences)
Last logged: 12:41:32

hyundai_kia_connect_api - error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":1005,"errorMessage":"Invalid vehicle for current session"}}
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:144
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:41:32 (1 occurrences)
Last logged: 12:41:32

[547261065648]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 35, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 75, in request_with_logging_wrapper
    raise AuthError
hyundai_kia_connect_api.KiaUvoAPIUSA.AuthError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 54, in async_handle_update
    await coordinator.async_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 144, in async_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 62, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 65, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 223, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 413, in _get_cached_vehicle_state
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 50, in request_with_active_session_wrapper
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 77, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```

**Comment by cdnninja** [comment]
Found a few issues for USA KIA and fixed them.  Please try updating your manifest to 1.52.2 for API version. 

Here was the PR for the fixes. https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/208

**Comment by nprez83** [comment]
No joy, It initially worked, but I then restarted my HA and the integration was again broken. I deleted and tried to readd it and I'm getting this errors.
```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:63
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 19:03:21 (2 occurrences)
Last logged: 19:03:38

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 164, in login
    response = requests.post(url, json=data, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by nprez83** [comment]
> No joy, It initially worked, but I then restarted my HA and the integration was again broken. I deleted and tried to readd it and I'm getting this errors.
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.kia_uvo.config_flow
> Source: custom_components/kia_uvo/config_flow.py:63
> Integration: Hyundai / Kia Connect (documentation, issues)
> First occurred: 19:03:21 (2 occurrences)
> Last logged: 19:03:38
> 
> Unexpected exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
>     response.begin()
>   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>   File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
>     response.begin()
>   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>   File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
>     await validate_input(self.hass, user_input)
>   File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
>     token: Token = await hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 164, in login
>     response = requests.post(url, json=data, headers=headers)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
>     return request("post", url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> ```

Actually, spoke too soon, looks like the Kia server is down again, as the native app is not working either. I'll wait a while and try again. Sorry for the fake news.

**Comment by cdnninja** [comment]
Sounds good.  As a note shouldn't need to reinstall.  It in theory recovers if the api is down once we get our side working.  I assume you are one of the first Kia usa user on 2.x.  We don't have many, so thank you for reporting these issues.

**Comment by nprez83** [comment]
All is working well so far, entities have not become unavailable since last night. I'm very happy to test this by the way. This integration is one of my daily drivers, so I really appreciate all the work you've put into it. We're hopefully going to upgrade to the Kia EV9 in a year or so, so I suspect this integration will continue to be one of my family's top ones no doubt.

**Comment by cdnninja** [comment]
Awesome glad to hear!   I will close this issue since I think the initial item is solved.  Feel free to take a look in the "data" sensor under attributes and let us know if you have items in that you would find helpful being a sensor.   Feel free to open issues for that or anything else.
