### ISSUE TITLE
Missing sensors - EV6

### ISSUE THREAD

**Issue by smierd** [Hyundai-Kia-Connect/kia_uvo#541]
**Region and Brand of car**
CA - Kia 2022 EV6 Long Range AWD
**Version of the integration**
2.3.1

**Describe the bug**
Upgraded from 1.8.3 and lost TPMS and Window Washer fluid sensors. Sensors aren't showing as unavailable or an invalid state, they simply don't appear as an entity.

Everything else working as expected.

**Comment by cdnninja** [comment]
If you update in HACS from "master" this should be solved. Could you test it out for me?

**Comment by smierd** [comment]
Not sure if I am doing things correctly. Looking at the HACS documentation I don't see a way to specify a a branch. That being said, it seems as if it is choosing the master branch because it is the same release version though I am not confident in that due to lack of experience.

I attempted to remove and re-install with no change in which sensors are available or missing.

**Comment by cdnninja** [comment]
If you select it in HACS and click redownload it will let you pick a version.   One in the list will be master.  This hasn't been released as a version yet.

**Comment by smierd** [comment]
Ah thank you for pointing that out. I redownloaded it from Master and everything is back again. Thank you for your help!
