### ISSUE TITLE
Unexpected error fetching kia_uvo data: float expected at most 1 argument, got 2

### ISSUE THREAD

**Issue by contrasenda** [Hyundai-Kia-Connect/kia_uvo#542]
**Region and Brand of car**
EU Hyundai Ioniq 5

**Version of the integration**
master

**Describe the bug**
After version 2.3.1, component didn't initialize with error 'ValueError: unconverted data remains: 0'. I redownloaded version master and component doesn't initialize either, with described exception (location masked in log).

**Debug logs if an error occurred**

```
2022-12-29 20:01:16.034 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: float expected at most 1 argument, got 2
File "/config/custom_components/kia_uvo/coordinator.py", line 102, in _async_update_data
File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_check_and_refresh_token
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 93, in check_and_refresh_token
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 55, in initialize
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 62, in update_all_vehicles_with_cached_state
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 65, in update_vehicle_with_cached_state
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 276, in update_vehicle_with_cached_state
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 459, in _update_vehicle_properties
```

`2022-12-29 20:00:53.619 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_cached_vehicle_status response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicleStatusInfo': {'vehicleLocation': {'coord': {'lat': xx.xxxxxx, 'lon': -x.xxxxx, 'type': 0}, 'head': 20, 'speed': {'value': 0, 'unit': 0}, 'time': '20221229172113'}, 'vehicleStatus': {'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTemp': {'value': '02H', 'unit': 0, 'hvacTempType': 1}, 'defrost': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 67, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 8, 'unit': 1}, 'etc2': {'value': 240, 'unit': 1}, 'etc3': {'value': 55, 'unit': 1}, 'atc': {'value': 240, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'evModeRange': {'value': 296, 'unit': 1}, 'totalAvailableRange': {'value': 296, 'unit': 1}}, 'type': 2}], 'reservChargeInfos': {'reservChargeInfo': {'reservChargeInfoDetail': {'reservInfo': {'day': [1, 2, 3, 4, 5], 'time': {'time': '0770', 'timeSection': 0}}, 'reservChargeSet': True, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': '12H', 'unit': 0, 'hvacTempType': 1}, 'airCtrl': 0, 'heating1': 0}}}, 'offpeakPowerInfo': {'offPeakPowerTime1': {'starttime': {'time': '1200', 'timeSection': 0}, 'endtime': {'time': '1200', 'timeSection': 0}}, 'offPeakPowerFlag': 1}, 'reserveChargeInfo2': {'reservChargeInfoDetail': {'reservInfo': {'day': [9], 'time': {'time': '0900', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': '12H', 'unit': 0, 'hvacTempType': 1}, 'airCtrl': 0, 'heating1': 0}}}, 'reservFlag': 0, 'ect': {'start': {'day': 0, 'time': {'time': '0000', 'timeSection': 0}}, 'end': {'day': 0, 'time': {'time': '0000', 'timeSection': 0}}}, 'targetSOClist': [{'targetSOClevel': 80, 'dte': {'rangeByFuel': {'evModeRange': {'value': 381, 'unit': 1}, 'totalAvailableRange': {'value': 381, 'unit': 1}}, 'type': 2}, 'plugType': 0}, {'targetSOClevel': 80, 'dte': {'rangeByFuel': {'evModeRange': {'value': 381, 'unit': 1}, 'totalAvailableRange': {'value': 381, 'unit': 1}}, 'type': 2}, 'plugType': 1}]}, 'chargePortDoorOpenStatus': 2, 'batteryPreconditioning': False}, 'ign3': False, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'sideBackWindowHeat': 0, 'tirePressureLamp': {'tirePressureLampAll': 0, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 85, 'batState': 0, 'sjbDeliveryMode': 0, 'batSignalReferenceValue': {'batWarning': 65}, 'powerAutoCutMode': 2}, 'lampWireStatus': {'stopLamp': {'stopLampStatus': False, 'leftLamp': False, 'rightLamp': False}, 'headLamp': {'headLampStatus': False, 'leftLowLamp': False, 'rightLowLamp': False, 'leftHighLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'rightBifuncLamp': False}, 'turnSignalLamp': {'turnSignalLampStatus': False, 'leftFrontLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'rightRearLamp': False}}, 'smartKeyBatteryWarning': False, 'washerFluidStatus': False, 'breakOilStatus': False, 'sleepModeCheck': True, 'time': '20221229143844', 'remoteWaitingTimeAlert': {'remoteControlAvailable': 1, 'remoteControlWaitingTime': 168, 'elapsedTime': '00:03:27'}, 'systemCutOffAlert': 0, 'tailLampStatus': 0, 'hazardStatus': 0}, 'odometer': {'value': 19781.4, 'unit': 1}}}, 'msgId': '0874f6e1-db2e-400c-ae11-96e40cf099eb'}`

**Comment by cdnninja** [comment]
I just fixed the above in master.  As 2.3.1 I suspect it was a different error so may still exist but I will need the stack trace to debug.

**Comment by contrasenda** [comment]
It's working perfectly now with latest master version. Thanks a lot!

**Comment by cdnninja** [comment]
Thank you!
