### ISSUE TITLE
Miles not Kilometres

### ISSUE THREAD

**Issue by pwlivewire** [Hyundai-Kia-Connect/kia_uvo#547]
**Is your feature request related to a problem? Please describe.**

I've seen several screenshots suggesting you can change the distance unit from kilometres to miles but this option is missing and suspect it's due to my region of EU/UK?

**Describe the solution you'd like**

Make the option and conversion appear

**Include the logs of the end point from Data in HA if this is a sensor**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/25018910/210188705-37e39ecc-e005-4f9a-90ea-8f0169548f56.png)

**Comment by cdnninja** [comment]
This is now on the sensor itself.  So select the Odometer sensor and it's in one of the tabs.

**Comment by pwlivewire** [comment]
change the sensor and looks fine, could do with documentation updating as I based my request on the intro page screenshot.

**Comment by cdnninja** [comment]
I think I tweaked some docs since the post.  Can you see if you see areas for improvement and create a PR if you do?
