### ISSUE TITLE
Seat Heating/Cooling Non-Functional

### ISSUE THREAD

**Issue by noltondyer** [Hyundai-Kia-Connect/kia_uvo#548]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
US - Hyundai (Tucson 2022)
**Version of the integration**
v2.3.3

**Describe the bug**
Upon calling the climate_start service and inputting the correct seat climate selections, I’ve found that none of the configurations work to start the car with the seat warmers/vents. 

I’m not sure how I could help as I’m relatively new to all of this, but I’m happy to try what I can with my Hyundai and going through logs.

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Call climate_start service,
Select seat climate control.

**Expected behavior**
The seats set their climate control based on their corresponding selection (2-8)
**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Seats currently haven't been implemented for the USA.  Can you confirm your mobile app supports it?

**Comment by noltondyer** [comment]
Yes! It is supported in the mobile app. (Screenshots included)

![FBB178E5-7AAC-45AF-A0DF-ECB6267B2A4A](https://user-images.githubusercontent.com/35444650/210437461-850fd939-b787-4186-9b4d-46e7fd9c64f7.png)
![Uploading F0FDAF5B-934D-4061-A6E3-72C5DF81B2C5.png…]()

**Comment by cdnninja** [comment]
How about if I add the same code as the canada side and we try see if it works?  Hyundai USA sniffing takes some effort to actually know what it should look like.

**Comment by noltondyer** [comment]
I've sniffed a command with a few seat options selected. Let me know what to send and I'll send it!

**Comment by cdnninja** [comment]
Amazing! I added what I think is correct here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/3eb49c29c78e642b619c33ecb7d43e46fdf81243/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py#L491-L507

In particular look at like 498-502.  If that looks correct to what you have sniffed update your manifest.json file API to 2.1.0 and give it a try.

**Comment by noltondyer** [comment]
This is the response that I got:

`url:   https://owners.hyundaiusa.com/content/myhyundai/us/en/page/dashboard.html airCtrl:   false igniOnDuration:   10 airTempvalue:   62 defrost:   false heating1:   0 gen:   2 regId:   <<REMOVED>>  seatHeaterVentInfo:   {"drvSeatHeatState":"8","rrSeatHeatState":"8","rlSeatHeatState":"8","astSeatHeatState":"5"}  service:   ignitionstart`

(Sorry for the jumbled mess, Im not quite sure how to lay everything out)

**Comment by cdnninja** [comment]
Okay I have adjusted the code to match the above.  The above looks to be from the website and not the app but it may be the same for this. 

Can you update your manifest to show 2.1.1 and let me know if it works?  If not try 2.1.0 as well.  A restart of HA will be required.

**Comment by noltondyer** [comment]
I'm sorry... how can I make sure its updated to show 2.1.1?

**Comment by cdnninja** [comment]
In your custom component directory edit the manifest.json file.   If unsure I can put it into this integration and have you use HACS was hoping to avoid that in case it breaks remote start for other USA users.

**Comment by noltondyer** [comment]
I sent over a message on Discord, I’ll give it a shot so you don’t have to risk breaking it!

**Comment by noltondyer** [comment]
Can confirm it is working with manifest updated to 2.1.1!

**Comment by cdnninja** [comment]
Amazing!!  This very possible is the first time this has been done outside the native app in any library.  I will bump the main branch with this version.

**Comment by noltondyer** [comment]
Beautiful! So glad I could help in some way! 👍
