### ISSUE TITLE
Missing/malfunctioning sensor: door lock status

### ISSUE THREAD

**Issue by elektrinis** [Hyundai-Kia-Connect/kia_uvo#550]
First of all thank you a lot for working on this integration a lot.

I have noticed that entity "lock.ioniq_5_door_lock" does not represent actual door lock status.
The app says it's locked, and I can physically see it's locked.
I have forced update and other data has updated, however this entity only shows it was unlocked some time ago.
![Screenshot 2023-01-06 094410](https://user-images.githubusercontent.com/15337792/210954643-240dcf1c-bdc9-4882-b7ca-a8522c845cfa.png)
![Screenshot_2023-01-06-09-45-03-670_com hyundai bluelink eu ux20-edit](https://user-images.githubusercontent.com/15337792/210954712-98b58e52-310d-489f-901c-2cc898da40ab.jpg)
![Screenshot 2023-01-06 094720](https://user-images.githubusercontent.com/15337792/210954834-e25d1433-5b0b-4d55-8697-31ca6223a1fa.png)

**Comment by cdnninja** [comment]
Which region? Is it always inverted?

**Comment by elektrinis** [comment]
Europe. It's not inverted, it's missing many events. It was locked yesterday evening around 6pm.
As you can see we were using the car, locking ang unlocking, but nothing in the log...

**Comment by cdnninja** [comment]
It will only update on scan. So either a force update which updates from the car. Or a cached call which sees what the cloud knows. This is shown by the last update sensor which is the last time the car checked in.

Careful with scan frequency as limits exist for calls.

**Comment by elektrinis** [comment]
I only do passive scan, as my battery already died once.
In this case you can see I did a force update and it did not update to correct status.
I will investigate further.

**Comment by cdnninja** [comment]
Enable debug logs and see what the logs are stating for lock status.

**Comment by cdnninja** [comment]
@elektrinis  Any update?

**Comment by elektrinis** [comment]
Thank you for keeping an eye.
I was further experimenting and it seems to be working fine. If I unlock the car via official app and then call a service to force update, if shows a correct status.
Not sure what happened previously, but I think it works as it should.
Again thank you, closing.
