### ISSUE TITLE
Working flow for password resets

### ISSUE THREAD

**Issue by davidski** [Hyundai-Kia-Connect/kia_uvo#552]
**Region and Brand of car**

USA / Hyundai

**Version of the integration**

v2.4.1

**Describe the bug**

What is the proper procedure for changing the password associated with an account? I reset my bluelink password outside of Home Assistant and had this integration lock my account. Upon unlocking my account, my attempts to change the password in this HACS integration via the configure dialog still result in an invalid access token error message. Should the existing configuration be deleted fully and a new device connection be established? I've already tried several combinations of disabling/enabling/restarting.

Thanks for the help!

**Comment by cdnninja** [comment]
Currently the only method is to remove and re add.  It is on my list to work on writing the re authentication flow.

**Comment by cdnninja** [comment]
Latest version from master will not lock out the account anymore for EU and CA.  It also has what I think is the change password flow, I haven't fully tested it though.

**Comment by davidski** [comment]
For anyone else coming across this issue, a remove and re-adding of the device configuration allowed me to use my new credentials.

**Comment by unsoluble** [comment]
Sorry to necro this, but... _how_ do you remove and re-add this? I've spent the last half-hour clicking around in the HA interface trying to find the thing to remove, without any luck. :)

**Comment by jblaze03** [comment]
> Sorry to necro this, but... _how_ do you remove and re-add this? I've spent the last half-hour clicking around in the HA interface trying to find the thing to remove, without any luck. :)

Settings > Devices & Services > Hyundai / Kia Connect (on the integrations tab)

![Image](https://github.com/user-attachments/assets/30a2c9f5-3a85-4b42-ad70-e10faa2cfb70)

click on the three dots in the hubs section and select delete.

**Comment by unsoluble** [comment]
Thanks! So many paths to things, never found that one. Now getting "unexpected error" with no further info on attempting to re-add, but will investigate that separately.
