### ISSUE TITLE
Missing Sensor: sensor.car.battery

### ISSUE THREAD

**Issue by kalel681** [Hyundai-Kia-Connect/kia_uvo#556]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada, Hyundai Kona EV

**Version of the integration**
2.4.1

**Describe the bug**
12v battery sensor seems to have disappeared with update to 2.4.1. Rollback to prior version does not show the sensor. 

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
It is listed in the attributes of the data sensor? And does it show in the mobile app?

**Comment by kalel681** [comment]
I doesn't show in the bluelink mobile app, but never has, even when it was available in HA.   
  

  
I see something under attributes that says "battery" with a different value than the SoC of the EV battery, but not sure if it's the 12v.   
  

  

  

  
  
  
  
  
>

**Comment by cdnninja** [comment]
Are you able to post the attributes?

**Comment by kalel681** [comment]
Sure thing. Here are all the data attributes. 
![Screenshot_20230106_215254_Home Assistant](https://user-images.githubusercontent.com/59033547/211126313-1f3f7504-4fea-40c1-a9e7-f1b3e2af43de.jpg)
![Screenshot_20230106_215335_Home Assistant](https://user-images.githubusercontent.com/59033547/211126314-7f53fd74-cb4c-4116-91a9-5a9e44f4f41d.jpg)
![Screenshot_20230106_215309_Home Assistant](https://user-images.githubusercontent.com/59033547/211126316-beaa4701-5887-4078-a856-275f8c7533cc.jpg)

**Comment by cdnninja** [comment]
So today we get battery from status.battery.batSoc could you look in the developer menu and state to confirm the indents appear to line up with the next status.battery.batSoc?  The screenshots don't show in that view.   I also believe this sensor changed type so that for EVs it will show the actual battery correctly so please take a second pass looking for the sensor.

**Comment by cdnninja** [comment]
Odd!  Any errors in the logs?

**Comment by kalel681** [comment]
Nothing in the log other than not getting location.

Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

**Comment by kalel681** [comment]
I just went in and looked again, and that sensor is back now. I'm not sure where it went, but wasn't there for almost 24 hours. Thanks for your help.
