### ISSUE TITLE
EV6 (USA) "Car Battery Level" Missing After 2.5.2 Update 

### ISSUE THREAD

**Issue by asktimfisher** [Hyundai-Kia-Connect/kia_uvo#564]
Title says it all. I'm referring to the 12V battery entity. I noticed because mine died and I've been watching it closely, only to no longer see it today.

**Comment by cdnninja** [comment]
Does it exist in your data attributes? I have seen Kia removing it for some users.

**Comment by cdnninja** [comment]
As well as a note force scanning often impacts your 12v.

**Comment by cdnninja** [comment]
Any updates before I close this?

**Comment by asktimfisher** [comment]
Thanks for the comments! No, it does not exist anywhere anymore. All I did was update to the latest version and it disappeared. Totally could have been another variable there I'm forgetting - I was doing lots of troubleshooting. So yeah, you can close it.

(And YES, pretty sure I killed the 12V with all the queries - UGH).

Thanks for trying to help!

**Comment by cdnninja** [comment]
I don't think the update did it but rather the restart gets you a new session. 

I would set force to 240 minutes and cached to 30.  Most important data updates auto occur when the car is turned off.
