### ISSUE TITLE
EV charge port entity - unavailable

### ISSUE THREAD

**Issue by elektrinis** [Hyundai-Kia-Connect/kia_uvo#569]
After latest update this happened. Am I the only one? IONIQ 5.
![Screenshot 2023-01-18 121500](https://user-images.githubusercontent.com/15337792/213145502-404a0c09-70cb-4da8-8bbf-71a46360128d.png)

**Comment by cdnninja** [comment]
What version did you come from and what version are you on? 

What region and brand? 

Could you post your data sensor attributes?

**Comment by cdnninja** [comment]
Any update? @elektrinis

**Comment by elektrinis** [comment]
Not sure what happened, but one entity was not showing up for some time. 
![Screenshot_2023-02-01-07-33-31-738_io homeassistant companion android-edit](https://user-images.githubusercontent.com/15337792/215960105-8ce3287e-e2ae-4695-b264-2b6eaac05059.jpg)

**Comment by cdnninja** [comment]
Most likely API server side.
