### ISSUE TITLE
12V battery level went unavailable

### ISSUE THREAD

**Issue by dblacknc** [Hyundai-Kia-Connect/kia_uvo#571]
US - 2021 Kia Niro PHEV

Integration 2.5.4 - latest

After working for about 24h, the 12V ("Car") battery level shows unavailable.   All other car queries look normal.
That level is actually the most desirable/important thing to me.  I'll enable debug logs and add those to this report.

![image](https://user-images.githubusercontent.com/1166211/213472324-9cbfaf07-2d56-47a1-babf-658715ee5b3a.png)

**Comment by cdnninja** [comment]
The attributes of the data sensor will show if you have the data coming from the api.  If not nothing we can do.  We have seen a few tickets created for this where it disappears in the USA and sometimes comes back later.

**Comment by dblacknc** [comment]
OK - thanks, I'll check.  The only change I made yesterday is decreasing the API polling from 30 to 15 min.   Will update here after poking around some more. 

Good to know some in the USA have seen it disappear on its own.

**Comment by dblacknc** [comment]
...and it just came back.  No idea why.  Closing since this is obviously not a problem with the integration.

**Comment by dblacknc** [comment]
FYI I've since determined the 12V ("Car") battery level is only available when the car is either running/being driven, or when actively charging the HV battery.   Outside of those two states, it's not provided in a vehicle info update.
