### ISSUE TITLE
Reported driving ranges for PHEV incorrect

### ISSUE THREAD

**Issue by dblacknc** [Hyundai-Kia-Connect/kia_uvo#572]
2021 Kia Niro PHEV
Integration 2.5.4

In the integration, I see reported:
Fuel Driving Range: 330 mi
Total Driving Range: 330 mi

The fuel range is incorrect, and EV range isn't reported.  Other aspects like EV SOC are present and correct.

Looking at the raw API response, here are some relevant parts:

                "drvDistance": [
                  {
                    "type": 1,
                    "rangeByFuel": {
                      "gasModeRange": {
                        "value": 306,
                        "unit": 3
                      },
                      "evModeRange": {
                        "value": 24,
                        "unit": 3
                      },
                      "totalAvailableRange": {
                        "value": 330,
                        "unit": 3
                      }
                    }
                  }
                ],
                "syncDate": {
                  "utc": "20230119164853",
                  "offset": -8
                },
                "targetSOC": [
                  {
                    "plugType": 1,
                    "targetSOClevel": 100,
                    "dte": {
                      "type": 1,
                      "rangeByFuel": {
                        "gasModeRange": {
                          "value": 306,
                          "unit": 3
                        },
                        "evModeRange": {
                          "value": 24,
                          "unit": 3
                        },
                        "totalAvailableRange": {
                          "value": 330,
                          "unit": 3
                        }
                      }
                    }
                  }
                ]

**Comment by cdnninja** [comment]
What region? This is unique depending on which api we use.

**Comment by dblacknc** [comment]
US

**Comment by cdnninja** [comment]
Thanks.  Looks like we are getting the fuel range from the following json location today: lastVehicleInfo.vehicleStatusRpt.vehicleStatus.distanceToEmpty.value

I assume that value is actually total available range on an EV, where as on a ICE it is the only range reported.  Could you validate for me?

**Comment by dblacknc** [comment]
Yes, distanceToEmpty on my PHEV and guessing also EV, the total estimated range.  From same response:

   "distanceToEmpty": {
                "value": 330,
                "unit": 3

**Comment by cdnninja** [comment]
In HACS could you redownload with the version of "Master" and let me know how it looks?

**Comment by cdnninja** [comment]
Awesome! Is ev range also showing now?

**Comment by dblacknc** [comment]
Sorry - yes, I was mistaken when opening the issue.  EV range has always been there, just missed it.
