### ISSUE TITLE
Climate for "Driver only"

### ISSUE THREAD

**Issue by sercanincesu** [Hyundai-Kia-Connect/kia_uvo#575]
Dear Sir,
I made automation to open climate every morning just 10 minute before going to work with your integration. When I seat car, I see not only driver side but also passenger side climate open unnecessarly. 

I mostly use car as daily to go to work by myself. That's why I always prefer to use climate option for "Driver only". That feature let climate only for the driver side, instead of changing climate for all car, that help to use energy consumption more efficiently. 

I would be happy, if you could add a feature for climaete automation that I can select "driver only" option.

**Comment by sercanincesu** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/118417017/213931910-093719d8-0c4a-466b-8647-f3c2ec4244cb.jpg)

**Comment by cdnninja** [comment]
Does this exist in the native app?

**Comment by sercanincesu** [comment]
It doesn't have on bluelink app. drive only option is only in car.
Can you add this feature, even if this feature doesn't exist in bluelink app?
For example these features that I marked with red rectangle in screenshot don't exist on bluelink app but you somehow add this function on your integration. 
![Screenshot_11](https://user-images.githubusercontent.com/118417017/213932972-1231ac48-a3e6-471b-83f4-99f32b61b195.jpg)
I hope you can make it for "drive only" option as well.

**Comment by cdnninja** [comment]
Seat control exists for select cars.  I'm shocked it actually works for you if you don't have it in app.   

Without it in someone's app I can't add it.

**Comment by sercanincesu** [comment]
Sorry for wrong information. As you said, seat heater option doesn't work with you integration because bluelink app doesn't have that function.

> Seat control exists for select cars. I'm shocked it actually works for you if you don't have it in app.
> 
> Without it in someone's app I can't add it.

**Comment by cdnninja** [comment]
I am closing as this won't be possible until the native app supports it.
