### ISSUE TITLE
EV Range unavailable

### ISSUE THREAD

**Issue by DandeMC** [Hyundai-Kia-Connect/kia_uvo#579]
**Region and Brand of car**
EU
**Version of the integration**
2.5.5

**Describe the bug**
The EV range showed after the update from 2.5.4 to 2.5.5 one time the range and now it stopped working on the newest version. It shows "unavailable".

**Debug logs if an error occurred**

Thats the only thing on the logs:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:126
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 12:00:27 (2 occurrences)
Last logged: 13:00:41

Force update failed, falling back to cached: Unavailable remote control - Service Temporary Unavailable
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 100, in check_and_force_update_vehicles
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 76, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 291, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 695, in _get_cached_vehicle_state
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 106, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.APIError: Unavailable remote control - Service Temporary Unavailable

**Comment by cdnninja** [comment]
Looks like the whole thing is temp unavailable.   This is common for the eu api. Should resolve on its own with time.

**Comment by DandeMC** [comment]
My problem is the EV range. That doesn't show...

**Comment by cdnninja** [comment]
The above error is a full failed update not just one item. So I suspect the above is unrelated.  

Could you post your data sensor attributes?

**Comment by DandeMC** [comment]
Where can I find the data sensor attributes?

**Comment by cdnninja** [comment]
Either click the data sensor on the device or go to developer menu and select the data entity on the device.   

Developer menu is more readable.

**Comment by DandeMC** [comment]
<img width="1037" alt="Greenshot 2023-01-26 15 22 37" src="https://user-images.githubusercontent.com/62901195/214859970-99cd654f-62f3-4b8f-81bd-87a6a7cd0314.png">

Do you mean this?

**Comment by Mkay505** [comment]
Yes - same issue here.

**Comment by cdnninja** [comment]
> <img alt="Greenshot 2023-01-26 15 22 37" width="1037" src="https://user-images.githubusercontent.com/62901195/214859970-99cd654f-62f3-4b8f-81bd-87a6a7cd0314.png">
> 
> Do you mean this?

Yes but the "data" entity.

**Comment by Mkay505** [comment]
What is the status of the original Kia App?
Mine is "-- km" although the battery is full.

cdnninja ***@***.***> schrieb am So., 29. Jan. 2023, 16:47:

**Comment by DandeMC** [comment]
> > <img alt="Greenshot 2023-01-26 15 22 37" width="1037" src="https://user-images.githubusercontent.com/62901195/214859970-99cd654f-62f3-4b8f-81bd-87a6a7cd0314.png">
> 
> > 
> 
> > Do you mean this?
> 
> 
> 
> Yes but the "data" entity. 

Can you show me a example? I don't know what you mean.

**Comment by cdnninja** [comment]
By a computer now.  So if you type "data" into the Entity spot on your screen.  The attributes will switch to the raw data we get on your car. 

![image](https://user-images.githubusercontent.com/6373468/215349583-ed67c2d0-8a1b-4b84-be83-3c30b944d5bb.png)

**Comment by DandeMC** [comment]
You mean this I think?

vehicle_data:
  vehicleLocation:
    coord:
      lat: 
      lon: 
      alt: 0
      type: 0
    head: 186
    speed:
      value: 0
      unit: 0
    accuracy:
      hdop: 0
      pdop: 0
    time: '20230129194021'
  vehicleStatus:
    airCtrlOn: false
    engine: false
    doorLock: true
    doorOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    trunkOpen: false
    airTemp:
      value: 00H
      unit: 0
      hvacTempType: 1
    defrost: false
    lowFuelLight: false
    acc: false
    evStatus:
      batteryCharge: false
      batteryStatus: 16
      batteryPlugin: 0
      remainTime2:
        etc2:
          value: 315
          unit: 1
        etc3:
          value: 115
          unit: 1
        atc:
          value: 25
          unit: 1
      drvDistance:
        - rangeByFuel:
            gasModeRange:
              value: 314
              unit: 1
            evModeRange:
              value: 0
              unit: 1
            totalAvailableRange:
              value: 314
              unit: 1
          type: 2
      reservChargeInfos:
        reservChargeInfo:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 1
                - 5
                - 6
              time:
                time: '1200'
                timeSection: 0
            reservChargeSet: false
        offpeakPowerInfo:
          offPeakPowerTime1:
            starttime:
              time: '1200'
              timeSection: 0
            endtime:
              time: '1200'
              timeSection: 0
          offPeakPowerFlag: 1
        reserveChargeInfo2:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 1
                - 2
                - 3
                - 4
                - 5
              time:
                time: '0330'
                timeSection: 1
            reservChargeSet: false
        reservFlag: 0
        ect:
          start:
            day: 0
            time:
              time: '0000'
              timeSection: 0
          end:
            day: 0
            time:
              time: '0000'
              timeSection: 0
    ign3: false
    hoodOpen: false
    transCond: true
    steerWheelHeat: 0
    sideBackWindowHeat: 0
    tirePressureLamp:
      tirePressureLampAll: 0
      tirePressureLampFL: 0
      tirePressureLampFR: 0
      tirePressureLampRL: 0
      tirePressureLampRR: 0
    seatHeaterVentState:
      frSeatHeatState: 2
      flSeatHeatState: 2
      rlSeatHeatState: 2
      rrSeatHeatState: 2
    battery:
      batSoc: 76
      batState: 0
      sjbDeliveryMode: 1
      batSignalReferenceValue:
        batWarning: 65
      powerAutoCutMode: 2
    lampWireStatus:
      stopLamp:
        stopLampStatus: false
        leftLamp: false
        rightLamp: false
      headLamp:
        headLampStatus: false
        leftLowLamp: false
        rightLowLamp: false
        leftHighLamp: false
        rightHighLamp: false
        leftBifuncLamp: false
        rightBifuncLamp: false
      turnSignalLamp:
        turnSignalLampStatus: false
        leftFrontLamp: false
        rightFrontLamp: false
        leftRearLamp: false
        rightRearLamp: false
    windowOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    smartKeyBatteryWarning: false
    fuelLevel: 63
    washerFluidStatus: false
    breakOilStatus: false
    sleepModeCheck: true
    time: '20230129194022'
    remoteWaitingTimeAlert:
      remoteControlAvailable: 1
      remoteControlWaitingTime: 168
      elapsedTime: '00:03:40'
    systemCutOffAlert: 0
    tailLampStatus: 0
    hazardStatus: 0
  odometer:
    value: 8130.4
    unit: 1
vehicle_name: SPORTAGE
friendly_name: SPORTAGE Data

**Comment by cdnninja** [comment]
Your range shows 0.  Do you see the sensor in home assistant at the moment and is 0 range correct?

**Comment by DandeMC** [comment]
It shows unavailable at the moment, not 0.

**Comment by cdnninja** [comment]
Okay,  I assume 0 range is correct though for the car.   I found what I think is the issue. https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/273

In about 5 minutes try update in hacs and select version "master".

**Comment by DandeMC** [comment]
Yes sorry. In my Kia App it shows 0. In HA it is unavailable.

**Comment by DandeMC** [comment]
do I have to delete everything in the master to be able to install? I am now on version 2.5.6. Is that right? I don't know how to switch an already installed version to master

**Comment by cdnninja** [comment]
No need to delete.  Go into HACS. Click on redownload on the integration and in the pop up where you select version select master.

**Comment by DandeMC** [comment]
Ok. I have done this. The version doesn't changed and the range is still unavailable.

**Comment by cdnninja** [comment]
Version number won't change since I didn't release.  Did you restart and do you know if EV range shows correctly when you have range?

**Comment by cdnninja** [comment]
I manually kicked a release for this as a way for you to confirm your update worked. 2.5.7 has this fix.

**Comment by DandeMC** [comment]
Now it looks like it will work. it shows 0km. I'll charge the car today and see if it works. Thank you!!!

**Comment by Mkay505** [comment]
After I charged the car, the battery indicator was 100%. The EV Range 0 km.

The current EV Range Status was only correct displayed after the car was
started and an update was triggered.

DandeMC ***@***.***> schrieb am Mo., 30. Jan. 2023, 07:05:

**Comment by DandeMC** [comment]
Now it shows only 0km. My car shows 18km.

**Comment by DandeMC** [comment]
Now I can see 8km distance. I think the problem 2 hours ago was on Kia, not your integration. Thank you for your help =)
