### ISSUE TITLE
Range Value shows 0 intermittently after periodic (Non-Forced) updates

### ISSUE THREAD

**Issue by mshivnan** [Hyundai-Kia-Connect/kia_uvo#586]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU / Kia eNiro
**Version of the integration**
HACS - 1.30.1
Kia Uvo / Hyundai Bluelink - v2.5.8

**Describe the bug**
The Range Values intermittently update with 0 when the periodic "Non-Forced" update occurs. The "Force Update" always returns the range value. This intermittent issue has been there since I deployed the integration last September however since the Feb update it seems to be happening more frequently

**Debug logs if an error occurred**
Not an error, just a zero value
Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Intermittent issue and seems to be happening more frequently since the Feb release

**Expected behavior**
Range should always show a non-zero value regardless of whether the update is passive or forced
**Screenshots**
Screenshot #1: Range entities showing 0 after passive update 2 hours ago
Screenshot #2: Range entities showing actual range after "Forced Update"
**Additional context**
![Range Issue - Passive](https://user-images.githubusercontent.com/113931352/216670315-53e841ab-965a-42f7-b4bc-f2f1c79d251c.jpg)
![Range Issue - Forced](https://user-images.githubusercontent.com/113931352/216670341-6710a510-15d0-4d98-a53f-a95c7c699c0d.jpg)

**Comment by cdnninja** [comment]
These ones are always a tough one.   Most likely this is the data from the car showing that.  When in that state can you compare to the native mobile app? As well compare to the attributes in your data sensor.

**Comment by mshivnan** [comment]
Thanks. I will do that the next time it happens and post my findings.

**Comment by mshivnan** [comment]
You are correct cdnninja. The range has dropped off again and confirmed that it has also dropped from the Kia Connect App. See attached. The car is due a service soon so I will ask that the Uvo system is fully updated in the car and hopefully that will sort it. Many thanks for your help on this and for creating this integration. 
![Kia Connect App with no Range](https://user-images.githubusercontent.com/113931352/216776200-f3a83072-07ca-4173-b268-68c8a741cd69.jpg)
![Range Issue - not coming from car](https://user-images.githubusercontent.com/113931352/216776210-094f71dd-9216-400d-99b9-52903c16d468.jpg)
