### ISSUE TITLE
EV Charge Port ==> Status unavailable

### ISSUE THREAD

**Issue by TMoersch** [Hyundai-Kia-Connect/kia_uvo#587]
Hi, 
I'am using the latest Version 2.5.8 of the Kia Uvo / Hyundai Bluelink HACS Integration in HomeAsssitent.
I Think two updates before this binary.sensor_xxxxxx_ev_charge_port  was still available.
Is this an known issue or is this sensor no longer supported?

Thanks to all for your support, Thomas

**Comment by cdnninja** [comment]
Could you check in the data sensor attributes if you have data related to the charge port or not?  This is the raw car data.

**Comment by TMoersch** [comment]
Hi, just did an HA Core Update to Version 2023.2.2 and guess what, Charge Port Status is now available again.
Thanks

**Comment by elektrinis** [comment]
charge port went unavailable for me few weeks ago. Latest HA/core.
Is it OK for you now?
