### ISSUE TITLE
22 Hyundai Santa Fe PHEV - USA - Lock / Unlock

### ISSUE THREAD

**Issue by instinxx** [Hyundai-Kia-Connect/kia_uvo#589]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
USA - Hyundai

**Version of the integration**
v2.5.9

**Describe the bug**
Clicking the Lock or Unlock button does not seem to work

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
Logging Enabled, no Hyundai log found

**To Reproduce**
Click Lock or Unlock

**Expected behavior**
Doors lock or unlock

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Without logs I can't assist.  To confirm you enable debug logging for both the api and the integration and the core logs make no reference?

**Comment by instinxx** [comment]
Wondering if related to https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/584#issue-1567186379

**Comment by cdnninja** [comment]
To confirm you provided your PIN when you setup the integration?

**Comment by instinxx** [comment]
I believe I did, is there a way to "re-add" it?

**Comment by cdnninja** [comment]
Remove the integration and re-add it.

**Comment by cdnninja** [comment]
@instinxx  any update?

**Comment by cdnninja** [comment]
Closing due to lack of reply.
