### ISSUE TITLE
Odometer shows up the wrong value

### ISSUE THREAD

**Issue by electricdelicate** [Hyundai-Kia-Connect/kia_uvo#594]
Ive found a bug at the Odometer sensor at my Hyundai Tucson PHEV.
It shows at driving the right value but a soon as I parking again the value fall back again to an old value and will be never changed.
Strange but the picture show you the problem exactly.
![grafik](https://user-images.githubusercontent.com/40469299/218149341-6369f67c-ccf4-4d39-9ca0-5df82e3c5161.png)
Between the red bars is the during driving status, what seems to be correct.

Newest version of HA and from the Addon via HACS are installed and the other sensors seems to be working properly.

Thanks for your help.

**Comment by cdnninja** [comment]
Validate if this is the same in the mobile app.  If so nothing we can really do.

**Comment by electricdelicate** [comment]
> Validate if this is the same in the mobile app. If so nothing we can really do.

Thanks for the hint and yes, in the Hyundai Bluelink App is the same issue. Weird ...

**Comment by cdnninja** [comment]
They are buggy unfortunately.   Nothing I can do to fix bad data from them in this case.

**Comment by electricdelicate** [comment]
Understand,

**Comment by caddyblack** [comment]
I had the same issue with my Kia Niro. The app also showed the wrong value. I contacted the service department of Kia. They pointed me to a newer car software version (version dec. 2023). After updating my car software the app showed the correct data and also Home Assistant showed the correct value again.

**Comment by electricdelicate** [comment]
> I had the same issue with my Kia Niro. The app also showed the wrong value. I contacted the service department of Kia. They pointed me to a newer car software version (version dec. 2023). After updating my car software the app showed the correct data and also Home Assistant showed the correct value again.

Many Thanks for the hint, I´ve just downloaded again the newest Hyundai Navigation Software Update and have installed it again on my Tucson.
Now it works, the kilometres update works as intended in the Mobile App and in Home Assistant as well.

Great! :)
