### ISSUE TITLE
Can't Install Integration

### ISSUE THREAD

**Issue by hexonMD** [Hyundai-Kia-Connect/kia_uvo#602]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada
2019 Kia Niro EV

**Version of the integration**
2.6.0

**Describe the bug**
Can't Install the plugin. Gives Generic Error. I was getting SSL errors before on my previous install and reinstalled the plugin to try and solve. 

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Setup Integration

**Expected behavior**

**Screenshots**

**Additional context**
<img width="542" alt="Screenshot 2023-02-28 at 8 34 54 PM" src="https://user-images.githubusercontent.com/3913256/222045730-b38c3811-75dc-4fd8-b944-8dec42ffdaa0.png">

**Comment by eric1090** [comment]
I have same issue (also in Canada)

**Comment by cdnninja** [comment]
I suspect this is caused by this: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/600  

Please try the latest release and see if it solves it.

**Comment by hexonMD** [comment]
Latest update fixed it

**Comment by eric1090** [comment]
Yes work perfectly now 😀
