### ISSUE TITLE
Server for car from Russia 

### ISSUE THREAD

**Issue by snagornyy** [Hyundai-Kia-Connect/kia_uvo#607]
Hi,
Thank you for great idea, but i can't use this integration: my car Hyundai from Russia
App uses server https://ru-ccapi.hyundai.ru
**Version of the integration**
v.2.6.1

Please help!

**Comment by cdnninja** [comment]
This is already an idea.  Please sniff the traffic.   Someone needs to reverse engineer the api.

**Comment by cdnninja** [comment]
This talks about it:  https://github.com/Hyundai-Kia-Connect/kia_uvo/discussions/474

I'll close this issue and continue over on that.
