### ISSUE TITLE
Unsupported language: en-GB, fallback to en

### ISSUE THREAD

**Issue by holdestmade** [Hyundai-Kia-Connect/kia_uvo#609]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU KIA

**Version of the integration**
2.6.1

**Describe the bug**
Getting Unsupported language: en-GB, fallback to en in the log

**Debug logs if an error occurred**

```
Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: custom_components/kia_uvo/config_flow.py:58
Integration: Hyundai / Kia Connect ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: March 13, 2023 at 8:46:05 PM (1 occurrences)
Last logged: March 13, 2023 at 8:46:05 PM

Unsupported language: en-GB, fallback to en
```

**Comment by capandcamera** [comment]
Is there a way to suppress this warning or correct the language?

**Comment by holdestmade** [comment]
I've added an exclusion in my logger so I don't see it

**Comment by capandcamera** [comment]
> I've added an exclusion in my logger so I don't see it

Good shout, done the same now. Cheers, completely forgot you can suppress specific messages.

**Comment by cdnninja** [comment]
It could be done in code.  I don't own a Kia anymore, so encourage someone to drop a PR for this.

**Comment by holdestmade** [comment]
Still getting this after updating to 2.16.2

**Comment by cdnninja** [comment]
This is a warning, are you saying it shouldn't tell you about this?  It is true you are using a language that kia API doesn't support so it can't use it.
