### ISSUE TITLE
Config Not Ready: Error communicating with API

### ISSUE THREAD

**Issue by metalux2030** [Hyundai-Kia-Connect/kia_uvo#613]
**Region and Brand of car**
2021 Hyundai Kona EV 
Germany

**Version of the integration**
v2.6.1

**Describe the bug**
When starting the integration and put my data in there will be the short message:
“Setup erneut versuchen: Config Not Ready: Error communicating with API: No Data Found v2 - No Data Found v2”

**Debug logs if an error occurred**
```
Logger: homeassistant.config_entries
Source: config_entries.py:1244
First occurred: 10:22:07 (1 occurrences)
Last logged: 10:22:07

Config entry 'Hyundai Europe XXXXX@mymail.com' for kia_uvo integration not ready yet: Config Not Ready: Error communicating with API: No Data Found v2 - No Data Found v2; Retrying in background
```

Thanks for help guys. I feel lost.

**Comment by cdnninja** [comment]
Does the car work corectly in the native app?

**Comment by metalux2030** [comment]
> Does the car work correctly in the native app?

Yes, without any problems.

**Comment by cdnninja** [comment]
Do you have a second car on the app that doesn't work?

**Comment by cdnninja** [comment]
The error means it logged in and fetched data but the server didn't have any data to give.  

If all cars in your app work enable debug logs and provide them.

**Comment by metalux2030** [comment]
> Do you have a second car on the app that doesn't work?

Hm, have an old car in the app that is no longer active. But I can't delete it in the app. Maybe that is the cause of the problem. Will try to get in touch with the Hyundai support first.

**Comment by cdnninja** [comment]
Yes that is.   Support can remove it.

**Comment by JuergenEhret** [comment]
Good evening, I hope that I place my contribution here correctly. Since yesterday I have problems with the integration that it gives me the following error "Config Not Ready: 'int_user_id'". In the app - week by the way works perfectly - Are 2 cars registered to me
