### ISSUE TITLE
Extra unlabelled toggle in Climate UI

### ISSUE THREAD

**Issue by Mod74** [Hyundai-Kia-Connect/kia_uvo#614]
**Region and Brand of car**
EU/UK, Kia (Niro EV)

**Version of the integration**
Latest/Not sure how to find in UI.

**Describe the bug**
There appears to be an extra unlabelled toggle in the Start Climate options between the Defrost checkbox and the Heating section. I suspect it might be to enable Heating, however from memory it doesn't need to be on if a "on" radio option is selected below.

**Debug logs if an error occurred**
N/A

**To Reproduce**
Call Climate On Service UI

**Expected behavior**
Labelled or clearer toggle purpose.

**Screenshots**
![image](https://user-images.githubusercontent.com/3301161/228678129-0f1cef9f-f1bc-4cdb-9c44-27eaf45ededa.png)

**Additional context**

**Comment by cdnninja** [comment]
The check mark puts defrost into the YAML.   The toggle turns it on or off.    

This is a home assistant gui thing.   Not if I can improve it.  All our items have that.  Check out seats as well.
