### ISSUE TITLE
Steering Wheel Heater On while the APP/car reports off

### ISSUE THREAD

**Issue by mvroosmalen1970** [Hyundai-Kia-Connect/kia_uvo#615]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Kia E-Niro EU/netherlands
 
**Version of the integration**
2021-04-20 20:41:05.424

**Describe the bug**
The Steering Wheel Heater = On while the APP/car reports off

**Debug logs if an error occurred**
E-NIRO Last Update changed to March 30, 2023 at 7:19 PM
7:20:52 PM - 7 minutes ago
E-NIRO Last Update changed to March 30, 2023 at 6:21 PM
6:21:43 PM - 1 hour ago
E-NIRO Steering Wheel Heater turned on
6:21:43 PM - 1 hour ago
E-NIRO Last Update changed to March 30, 2023 at 4:13 PM
4:21:00 PM - 3 hours ago
E-NIRO Steering Wheel Heater turned off
4:21:00 PM - 3 hours ago
E-NIRO Last Update changed to March 30, 2023 at 3:51 PM
3:51:36 PM - 4 hours ago
E-NIRO Last Update changed to March 30, 2023 at 1:34 PM
1:50:51 PM - 6 hours ago
E-NIRO Last Update changed to March 30, 2023 at 11:29 AM

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Am I correct in saying you are on a version from 2 years ago?  Typically they are version numbers note dates.

**Comment by mvroosmalen1970** [comment]
Haha, my mistake. This is my cars version:
![image](https://user-images.githubusercontent.com/36565907/228933869-e22f0950-cbca-432c-8436-70311b1a4c81.png)
Where is the version ?? Noted that the file dates are 07 oct 2022 17:33:39 GMT

**Comment by cdnninja** [comment]
You are on the legacy version.  The new version is a breaking change so make sure you have some time to correct automations or what not.   

At this point the old version isn't supported.

**Comment by mvroosmalen1970** [comment]
Ok. Is the new version pushed via HACS or in the HA as regular intergration?

**Comment by cdnninja** [comment]
HACS.

**Comment by mvroosmalen1970** [comment]
after upgrade (does not show in HACS as regular update) the problem is gone! Thanks for the suggestion
