### ISSUE TITLE
Display the EV battery temperature? 

### ISSUE THREAD

**Issue by Tabbe70** [Hyundai-Kia-Connect/kia_uvo#620]
Hi, have been using this and it works fine inside HA. 
I have a KIA EV6 in EU
Is it possible to get the EV battery temperature and a symbol gor pre-Heating ? 
It should really helpful to see info regarding battery pre-heating that start automaticly when drivning long range and you look for fastest (shortest) possible charging time.

**Comment by cdnninja** [comment]
Is this in app?

**Comment by Tabbe70** [comment]
No, not in the KiaConnect.
You need to use OD2B connection to reach this at the moment.

/TB

Den tors 6 apr. 2023 23:39cdnninja ***@***.***> skrev:

**Comment by cdnninja** [comment]
Then not something we can add.
