### ISSUE TITLE
Expose scheduled charge/climate control as sensor

### ISSUE THREAD

**Issue by sammort** [Hyundai-Kia-Connect/kia_uvo#627]
Hey thanks for the great work on this API and integration with HA, it's really helpful to be able to setup some more advanced automations.

I hoped it might be possible to see the status of scheduled charging/climate control as a binary sensor in HA. My use case is this:

I usually only want my EV to charge during the 'off-peak' tariff, and this mostly works well when scheduled charging is set and enabled in the Bluelink app. However, frustratingly the setting will (seemingly at random) reset and scheduled charging is no longer enabled. This usually results in someone plugging in the car and not noticing that it immediately starts to charge (costing an arm and a leg with the current energy prices!)

It would be great to be able to detect this 'reset' using this API's integration with HA, by exposing this setting as a sensor in the app, would this be possible?

(This is similar to request in https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/18)

**Comment by erelke** [comment]
I marked with red missing datas - from my Kia Connect app (Niro EV MY20/EU)
![IMG_20230415_105905](https://user-images.githubusercontent.com/30900475/232202929-a746e545-27e9-4363-82f5-d26332d5cf34.jpg)
![IMG_20230415_110021](https://user-images.githubusercontent.com/30900475/232202931-f02f687b-14ae-45bc-b7ca-426ac3240879.jpg)

**Comment by erelke** [comment]
Charging completion alert settings also missing from HA
![Screenshot_2023-04-15-11-07-10-688_com kia connect eu](https://user-images.githubusercontent.com/30900475/232203111-d9ce5c3e-d148-4a3c-98a8-b353621fded8.jpg)

**Comment by kalaws** [comment]
Would it be possible to show the date and/or day of week for which charging has been scheduled?

**Comment by DJBenson** [comment]
Is it possible to expose the below as controls rather than sensors?

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/1013909/d21b5c49-b51b-404e-b56f-ac5faf07546b)

**Comment by cdnninja** [comment]
All of this is possible just need someone to write and test it. I don't have a Kia anymore so less invested. I also didn't have an EV so hard to test.

**Comment by sammort** [comment]
It was possible to build an automation to notify when this value had reset in Bluelink by watching for changes in value of _Off Peak End Time_ and _Off Peak Start Time_. When both of these values = 00:00:00 then the off-peak charging values had been reset.

Closing this issue as no additional work required to achieve what is intended in this request.
