### ISSUE TITLE
Unnecessary conversion is being done

### ISSUE THREAD

**Issue by fuatakgun** [Hyundai-Kia-Connect/kia_uvo#63]
- rangeByFuel:
evModeRange:
value: 223.06796
unit: 3
totalAvailableRange:
value: 223.06796
unit: 3
type: 2

After first forced update I see

<img width="481" alt="Screenshot 2021-09-17 at 18 43 41" src="https://user-images.githubusercontent.com/47116236/133831432-78a47daf-1ab1-45fb-b76c-86c8b70f639f.png">

But then after doing a second forced update I get

- rangeByFuel:
evModeRange:
value: 213.74757
unit: 3
totalAvailableRange:
value: 213.74757
unit: 3
type: 2

<img width="486" alt="Screenshot 2021-09-17 at 18 45 16" src="https://user-images.githubusercontent.com/47116236/133831741-07de4a3c-af32-415f-af06-4c1c46743b4b.png">

Was being driven about between updates hence the range difference from 223 to 213

_Originally posted by @gadgetshed in https://github.com/fuatakgun/kia_uvo/issues/61#issuecomment-921971624_

**Comment by fuatakgun** [comment]
when this issue happens again, can you just `update` rather than `force update` ?

**Comment by gadgetshed** [comment]
Yeah will do and I'll capture all the other data to see if anything else in data changes.

**Comment by gadgetshed** [comment]
Before update - range 1st icon on second line

![image](https://user-images.githubusercontent.com/47116236/133843976-a33bf50a-6c5c-4a4f-89e6-071ef081486d.png)

![image](https://user-images.githubusercontent.com/47116236/133843986-5f832bda-aaba-4d1b-b945-4b49b96ffd72.png)

Then pressed update button
![image](https://user-images.githubusercontent.com/47116236/133844083-0e33bbfa-3212-43bb-8b27-26ea08717986.png)

![image](https://user-images.githubusercontent.com/47116236/133844100-81778a4d-55fe-48cf-9bc3-198f604b398b.png)

**Comment by cdnninja** [comment]
Is this still occurring in 2.x?

**Comment by DavidBSteele** [comment]
I'm currently on 1.8.5. I've just kicked off an update so I'll report back when I've validated.

**Comment by cdnninja** [comment]
@DavidBSteele how does this look?

**Comment by DavidBSteele** [comment]
It's not happened since the upgrade. So looks good. 

If it does happen again I'll post a new issue.

Nice work. Thanks.
