### ISSUE TITLE
Fuel level sensor missing

### ISSUE THREAD

**Issue by never102** [Hyundai-Kia-Connect/kia_uvo#630]
**Region and Brand of car**
Canada, Santa Fe PHEV

**Version of the integration**
v2.8.1

**Describe the bug**
Recently updated from a fairly old version, and while cleaning up my dashboards from the API changes noticed that I was missing the "fuel level" sensor.  The Blue Link app still shows the fuel level as a percentage. 

**Debug logs if an error occurred**
`2023-04-17 22:42:30.070 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kia_uvo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-17 22:43:52.850 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: kia_uvo
2023-04-17 22:44:43.762 WARNING (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get vehicle location failed
2023-04-17 22:44:43.791 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 122.037 seconds (success: True)
2023-04-17 22:44:44.641 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.796 seconds (success: True)`

**To Reproduce**
Unknown

**Expected behavior**
Fuel level should be a sensor returned from the integration.

**Screenshots**
<img width="316" alt="image" src="https://user-images.githubusercontent.com/34526429/232674504-c78cf29b-d105-41c7-90d3-d1653c2cba57.png">

**Comment by cdnninja** [comment]
Could you reload the integration and see if it comes back?

**Comment by never102** [comment]
> Could you reload the integration and see if it comes back?

Yeah, I've done that a few times and just tried again (have even restarted HA a few times).  Still no dice.  Should I try removing the integration completely and re-adding it?

**Comment by cdnninja** [comment]
Re adding won't help.  I have seen the api stop providing this data before and it returns later.    Can you check the attributes of the data sensor to see if it lists this data? This is the raw api response.

**Comment by never102** [comment]
Sorry for the delay @cdnninja - just got home from the hospital with our first little one!

So the data sensor seems to show it:
`fuelLevel: 64`

**Comment by cdnninja** [comment]
Where in the tree is that? In the debug menu it will show the indents.

**Comment by cdnninja** [comment]
@never102  congrats by the way! Enjoy the time!

**Comment by never102** [comment]
> Where in the tree is that? In the debug menu it will show the indents.

Do you mean in the attributes list?

And thank you!!!

`Attributes
Vehicle data
status:
lastStatusDate: '20230427231236'
airCtrlOn: false
engine: false
doorLock: false
doorOpen:
frontLeft: 0
frontRight: 0
backLeft: 0
backRight: 0
trunkOpen: false
airTempUnit: C
airTemp:
value: 14
unit: 0
defrost: false
lowFuelLight: false
acc: false
evStatus:
batteryCharge: true
batteryStatus: 50
batteryPlugin: 3
remainTime:
- value: 380
unit: 1
remainTime2:
etc2:
value: 380
unit: 1
etc3:
value: 145
unit: 1
atc:
value: 380
unit: 1
drvDistance:
- rangeByFuel:
gasModeRange:
value: 434
unit: 1
evModeRange:
value: 1
unit: 1
totalAvailableRange:
value: 435
unit: 1
type: 1
hoodOpen: false
transCond: true
steerWheelHeat: 0
sideBackWindowHeat: 0
dte:
value: 435
unit: 1
tirePressureLamp:
tirePressureLampAll: 0
tirePressureLampFL: 0
tirePressureLampFR: 0
tirePressureLampRL: 0
tirePressureLampRR: 0
battery:
batState: 0
sjbDeliveryMode: 0
batSignalReferenceValue: {}
remoteIgnition: true
seatHeaterVentInfo:
drvSeatHeatState: 2
astSeatHeatState: 2
rlSeatHeatState: 2
rrSeatHeatState: 2
lampWireStatus:
headLamp:
headLampStatus: false
leftBifuncLamp: false
rightBifuncLamp: false
stopLamp:
stopLampStatus: false
leftLamp: false
rightLamp: false
turnSignalLamp:
turnSignalLampStatus: false
leftFrontLamp: false
rightFrontLamp: false
leftRearLamp: false
rightRearLamp: false
windowOpen: {}
smartKeyBatteryWarning: false
fuelLevel: 55
washerFluidStatus: false
breakOilStatus: false
engineOilStatus: false
vehicleMovementHis: true
engineRuntime:
value: 0
unit: 1
vehicleLocation: null
service:
msopServiceOdometer: 23000
msopServiceOdometerUnit: 1
mtspServiceDate: '20230223'
imatServiceOdometer: 31000
imatServiceOdometerUnit: 1
mtitServiceDate: '20230823'
currentOdometer: 24446.5
currentOdometerUnit: 1
serviceOdometerDuration: 8000
serviceDaysDuration: 180
serviceMonthsThreshold: 6
Vehicle name
SANTA FE`

**Comment by never102** [comment]
oh, @cdnninja - not sure if I was supposed to tag you :)

**Comment by cdnninja** [comment]
Could you test on the latest and let me know if it works?

**Comment by never102** [comment]
I’ll do it tonight, thank you!!

**Comment by never102** [comment]
@cdnninja Fixed!! Thank you so much!

<img width="514" alt="image" src="https://user-images.githubusercontent.com/34526429/235568907-8ec8e54f-dbfa-450b-99b8-a08dbd7af71c.png">
