### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by NissarAK84** [Hyundai-Kia-Connect/kia_uvo#632]
Hi,
This has been working for me until recently where I would get connection error. I tried many times to reload the integration and it didn't help.

Today I deleted it and now when I try to add it again and want to login using my Bluelink credentials I am getting unexpected error message.

I have a Hyundai Ioniq 5 EV. I live in EU.

Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**

**Describe the bug**

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by NissarAK84** [comment]
![image](https://user-images.githubusercontent.com/126121308/233446137-2a3f6990-231b-4b3c-9eac-dcfdb04a14f1.png)

**Comment by cdnninja** [comment]
What version?

**Comment by NissarAK84** [comment]
I have the latest one available on HACS. I did an upgrade of my HA and now it's working.
