### ISSUE TITLE
Error: Config flow could not be loaded

### ISSUE THREAD

**Issue by Ludde157** [Hyundai-Kia-Connect/kia_uvo#635]
Hello,
I own a Kia Ceed, I would like to add this integration to Home Assistant. 

But when I try to add this integration I receive this: "error: Config flow could not be loaded"

Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**

**Describe the bug**

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Could you go through and answer the other questions in the template? What version of the integration region and brand? What error shows in the actual logs?

**Comment by Kagey-cmd** [comment]
Duplicate of #643

**Comment by cdnninja** [comment]
If it's Canada ssl errors yes some OS changes have happened that block weak encryption which Kia Hyundai Canada use.   I have been finding it hard to make this work on all potential installs.

**Comment by cdnninja** [comment]
Is this on going?

**Comment by MYG63** [comment]
> Is this on going?

For me that can be closed. Sometimes connection with Kia servers stuck but thats another issue.
