### ISSUE TITLE
Kia : Exceeds number of requests

### ISSUE THREAD

**Issue by luckyzor** [Hyundai-Kia-Connect/kia_uvo#636]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU Kia Sportage 
**Version of the integration**
Last

**Describe the bug**
Having the: Exceeds number of requests

It started today with this issue, how many requests can we do within 24h?
Could this be a bug because of to many requests made by the integration?
Should I reduce the requests in the integration?
For now I had it, all the 15 min and it worked for months like that.

**Comment by cdnninja** [comment]
What are you configured for? This shows estimated limits: https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits

Assuming unchanged.

**Comment by fuatakgun** [comment]
Too frequent calls might also harm car battery

**Comment by nerdybynature** [comment]
I also experience this with the default settings:
![image](https://user-images.githubusercontent.com/1333979/235304736-c2e4b18f-4a76-473b-9058-5279b7db0349.png)

> Too frequent calls might also harm car battery
Frequent **force refresh** calls or all calls?

**Comment by a-schiffer** [comment]
Only force calls - as they wake up the car.
Let me give an example what "frequent" means:
My electric Kona is two months old.
After a long drive the 12V-battery was completely filled.
I didn't use the car for 1.5 days, but I made between 150 and 200 force calls to it.
After that, the car couldn't start anymore and it even wasn't possible to open the trunk.
I needed external electric help to the 12V-battery to start the car.
(The big 64 kWh-battery was still nearly filled).

And by the way - with regards to the daily request limit: Here in Europe, the limit is around 200 calls per day - but also cache calls count, not only force calls.

**Comment by nerdybynature** [comment]
I did also notice this on my phone (Samsung S21):
![image](https://user-images.githubusercontent.com/1333979/235305645-ebf6d1fa-9ac0-4d89-84b5-4dc79fc5c56b.png)

It complains about Bluelink frequently waking up. Might be related.

@a-schiffer But still, the default settings shouldn't exceed the 200 call limit. If I math correct it should be 48 cache calls + 6 force refreshes (not taking the quite hours into account).
Sure, that's only calls from the integration, I haven't checked how often the Bluelink app is requesting data.

**Comment by cdnninja** [comment]
It is for the user so if your native app is acting up it could do this.

**Comment by olivierjag2** [comment]
I have same issue do you have fix?

**Comment by cdnninja** [comment]
Do you have the native app also consuming battery? This may be unrelated to the integration.

**Comment by Paytrix** [comment]
I get the same error when trying to login to the UVO / Kia Connect

**Comment by TraipZe** [comment]
When Will cached value change ?
Lets say soc is 80% then it charge to 82% will next scan cache the 80 or 82?

**Comment by liamhildebrand** [comment]
I have the same, 200 is the max for now
