### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by sacua** [Hyundai-Kia-Connect/kia_uvo#638]
**Region and Brand of car**
Kia Niro EV, Canada
**Version of the integration**
2.9.0

**Describe the bug**
Not able to config the integration since the update. Going to the previous version of does not solve the problem as well. So, nothing works.

**Debug logs if an error occurred**
Logger: homeassistant.config_entries
Source: config_entries.py:1247
First occurred: 7:48:46 PM (1 occurrences)
Last logged: 7:48:46 PM

Config entry 'Kia Canada samuel.c.auclair@gmail.com' for kia_uvo integration not ready yet: Config Not Ready: HTTPSConnectionPool(host='kiaconnect.ca', port=443): Max retries exceeded with url: /tods/api/lgn (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1007)'))); Retrying in background

**Comment by cdnninja** [comment]
What platform are you running on?

**Comment by sacua** [comment]
On a raspberry pi with HA in a container

**Comment by cdnninja** [comment]
What version of ha?

**Comment by sacua** [comment]
The last one 2023.5.0

**Comment by xKronyx** [comment]
Same here on the latest version of HA

**Comment by xKronyx** [comment]
still the same error with the  2023.5.1 update

**Comment by sacua** [comment]
If that can help you, I've rolled back my home assistant core to 2023.4.6 and it is working.

**Comment by keithajmani** [comment]
Same issue here on 2023.5.2 .. tried rolling back to 2.8.1 and it persists, so it definitely seems related to the HA upgrade.

**Comment by cdnninja** [comment]
Looks like home assistant made a change that forces certain cipher suits.  This change overrides my code that allows older ones.  

Canada Hyundai Kia use an old one for some reason.   

I'll have to see if I can fix this or if I have to get home assistant core to resolve this.

**Comment by cdnninja** [comment]
Could you try on the latest? I think I have it resolved.

**Comment by sacua** [comment]
I confirm, it is working ! Thanks

**Comment by keithajmani** [comment]
Also confirming that v2.10.0 works now for me on HA 2023.5.2. Thank you!

**Comment by xKronyx** [comment]
It works to ! thanks !
