### ISSUE TITLE
State_class of the odometer sensor

### ISSUE THREAD

**Issue by MobilettoSoft** [Hyundai-Kia-Connect/kia_uvo#641]
**Region and Brand of car**

Hyundai EU

**Version of the integration**

2.10.0

**Describe the bug**

The odometer sensor has state_class: measurement

**Expected behavior**

Probably, state_class: total_increasing should be the most suitable option, considering that this is a value that is only destined to increase. 
Moreover this should resolve some erratical statistics when the sensor becomes unavailable (statistics card and graphs,  daily mileage when feeding an utilty meter etc)

**Comment by cdnninja** [comment]
You sound familiar with how this works.  Could you drop a PR?

**Comment by MobilettoSoft** [comment]
Well, I'm quite familiar with homeassistant config, so I've changed the state_class using entity customization in configuration.yaml and it seems to work.
I'm not so familiar with integrations coding. However I guess I've identified where the state_class is set, so I can try to drop a PR.
