### ISSUE TITLE
start stop charge, set charge limits not avaible

### ISSUE THREAD

**Issue by laurh77** [Hyundai-Kia-Connect/kia_uvo#649]
Hello
Kia Niro EV, last version of integration (2.10.2)
Only charge limit and Unlock option avaible
Is a bug or I do something wrong ?

Thank you

Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**

**Describe the bug**

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
We are going to need more detail.

**Comment by laurh77** [comment]
What I am trying to say is that the only control in HA is Charging limit (AC and DC) and Door lock/unlock.
I do not have the possibility to start/stop charging, to set the charging speed ...
Do I do something wrong ?
![Screenshot_20230603-081725_Home Assistant](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/74540172/2d42ef24-9028-4454-b5a3-baaddb226200)

**Comment by cdnninja** [comment]
Go into developer services menu.

**Comment by laurh77** [comment]
can you please be more specific ?

**Comment by cdnninja** [comment]
Click developer tools. Click services. Search kia_uvo.

**Comment by laurh77** [comment]
Found it
Thank you very much
