### ISSUE TITLE
12v battery status is 255 % after max load

### ISSUE THREAD

**Issue by aswdo** [Hyundai-Kia-Connect/kia_uvo#653]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**

**Describe the bug**

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
This is bad data from kia Hyundai.  When this occurs check your native app.  In the past also wasn't right.   If that's the case open a ticket with kia Hyundai.

**Comment by ministryofsillywalks** [comment]
I know this is closed but I have exactly the same issue.
Nowhere inside the bluelink app I can find the 12v battery readings to confirm the bad data.
@aswdo did you manage to fix this?
