### ISSUE TITLE
KIA EV6, Charge level

### ISSUE THREAD

**Issue by cdnninja** [Hyundai-Kia-Connect/kia_uvo#655]
### Discussed in https://github.com/Hyundai-Kia-Connect/kia_uvo/discussions/651

<div type='discussions-op-text'>

<sup>Originally posted by **chersoph** June  1, 2023</sup>
In the Kia Connect app, there is information about the Battery level (Status- Charging & Climate - Battery Level). It is not the same value as the "sensor.ev6_car_battery_level", that i suspect is the 12V battery. For instance at this moment 98% for sensor.ev6_car_battery_level and the app battery level is 83%.
Can the app battery level be added to the list of attributes/sensors in the integration? 
</div>

**Comment by cdnninja** [comment]
@chersoph  The mapping looks to exist.  To confirm you don't have "EV Battery Level" as a sensor? You should have both that and car battery. 

If not please post the version you are running.

**Comment by chersoph** [comment]
I have v2.10.2 installed
//Erik

**Comment by chersoph** [comment]
Hello,
I'm so sorry for taking up your time. I realize that I actually have the
sensor, "sensor.ev6_ev_battery_level"
//Erik

Den ons 7 juni 2023 kl 05:32 skrev cdnninja ***@***.***>:
