### ISSUE TITLE
Recirculation toggle function

### ISSUE THREAD

**Issue by rikardkjell** [Hyundai-Kia-Connect/kia_uvo#659]
It would be a more afficient cooling/warming of the car if one could do that with the recirculation function activated.

Possible to turn on the recirculation function in the car and that from the service "Kia Uvo / Hyundai Bluelink: start_climate".

**Comment by cdnninja** [comment]
What region? As well do you have this in your native app?

**Comment by rikardkjell** [comment]
Ooops. A case of wishful thinking... EU-region but not present in the native app.

**Comment by cdnninja** [comment]
Sadly can't be done if that is the case.
