### ISSUE TITLE
Connect Error with Docker Installation

### ISSUE THREAD

**Issue by nikmaier** [Hyundai-Kia-Connect/kia_uvo#665]
Hello,
i have a Problem with the Login.
I have an Home Assistant OS to test, there the login is ok.
But on my Dockers Installation with an Rasperry there i become this error when i want to login:

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/69574329/e9546743-c8e3-48bc-ae4f-10028b64d35a)

Can anyone help?

Thanks a lot

**Comment by fuatakgun** [comment]
if you need hep, you need to follow the bug template and put all the required information there

**Comment by nikmaier** [comment]
Oh, ok sorry, here the template:

Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe Germany Kia EV6 GT 2023

**Version of the integration**
current v2.10.2

**Describe the bug**
A clear and concise description of what the bug is.

When i want to login, i become immediately an error: "Unbekannter Fehler" (englisch: "unknown error")

**Debug logs if an error occurred**
`Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:63
Integration: Hyundai / Kia Connect ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 29. Juni 2023 um 08:53:04 (8 occurrences)
Last logged: 12:45:58

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 198, in login
    device_id = self._get_device_id(stamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1104, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 110, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'`

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md


**To Reproduce**
yes

**Expected behavior**
?

**Screenshots**
If applicable, add screenshots to help explain your problem.
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/69574329/e9546743-c8e3-48bc-ae4f-10028b64d35a)


**Additional context**
I have an Home Assistant OS to test, there the login is ok.
But on my Dockers Installation with an Rasperry there i become this error

**Comment by fuatakgun** [comment]
should be related to this: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/660

not specific to your setup but an overall issue impacting EU

**Comment by nikmaier** [comment]
Oh, thank you

**Comment by HansNetcom** [comment]
Same issue here wit my Kia eNero. Worked perfect in the recent past
