### ISSUE TITLE
Cannot load configuration wizard

### ISSUE THREAD

**Issue by SteffeyDev** [Hyundai-Kia-Connect/kia_uvo#670]
**Version of the integration**
2.10.4

**Describe the bug**
When I go to add the integration, it gets stuck on loading the configuration wizard:
```
Please wait, starting configuration wizard for kia_uvo
```

**Debug logs if an error occurred**
There are no logs in the server log or browser console logs

**To Reproduce**
Go to Integrations > Add Integration

**Expected behavior**
The configuration wizard loads

**Screenshots**
<img width="555" alt="Screen Shot 2023-07-03 at 3 12 15 PM" src="https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/10255587/6fded7e7-6f08-4fd2-865d-943cb198c4af">

**Additional context**
Tried in Safari and Firefox
Have waited 5 minutes, nothing changes

**Comment by cdnninja** [comment]
If no logs restart home assistant and try again.
