### ISSUE TITLE
Anmeldung wieder möglich

### ISSUE THREAD

**Issue by rhiermei** [Hyundai-Kia-Connect/kia_uvo#674]
Nachdem tagelang die ANmeldung am Service nicht mehr möglich war habe ich heute die Integration gelöscht und neu installiert.
Danach wurde ein Update angezeigt.
- Update installiert
- Neu angemeldet (Anmeldung dauert sehr lange)
- alles geht wieder wie vorher.

**Comment by cdnninja** [comment]
Are you requesting help or just saying our update resolved your issue?  EU had large issues and updates have been released.  Still issues remain though.

**Comment by SCORRPiO** [comment]
Issue can closed. The Update have resolved the issue.
