### ISSUE TITLE
UVO end of life

### ISSUE THREAD

**Issue by pwlivewire** [Hyundai-Kia-Connect/kia_uvo#675]
KIA UK have confirmed they are ending UVO as an app and all future development will be done in the KIA connect app.

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/25018910/790a98a2-677c-4f52-ba9d-8375120b4c1b)

Can this be merged with;

https://github.com/PimDoos/kia_connect

**Comment by cdnninja** [comment]
What you linked is Kia connected services. That predates UVO.    We are using the connect app id and working to move to those endpoints.  That's what caused the recent outage in this integration and the ongoing issues.
