### ISSUE TITLE
2 Vehicles in one Account

### ISSUE THREAD

**Issue by leetillu** [Hyundai-Kia-Connect/kia_uvo#684]
**Is your feature request related to a problem? Please describe.**
I have two cars in one Kia Account, I can only add the account once, so I can not see the second car.

**Describe the solution you'd like**
Make it possible to differentiante between 2 cars / parallel

**Include the logs of the end point from Data in HA if this is a sensor**

**Describe alternatives you've considered**
I have thought about splitting the two cars into two accounts, but that will make it bothersome with the Kia Mobile App.

**Additional context**
![grafik](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/132269585/adbeac2c-ecca-45a8-9532-0b61cd69a9cf)

**Comment by cdnninja** [comment]
Which region? I thought this already worked. Any logs you can provide?

**Comment by leetillu** [comment]
It seems that this problem has solved itself somehow, meanwhile the two cars are both visible and provide data.
Maybe it was because of the recent changes to the API.. can be closed :-)
