### ISSUE TITLE
Typo in sensor name

### ISSUE THREAD

**Issue by kalaws** [Hyundai-Kia-Connect/kia_uvo#685]
Small typo report
Is:
First Scheduled Depature Time

Should be:
First Scheduled Depa[r]ture Time

Thanks for the great work.

**Comment by cdnninja** [comment]
Good catch.  Just did this to solve it: https://github.com/Hyundai-Kia-Connect/kia_uvo/commit/0a1fd64a1ad8d2eb31bea02ecf06498716923221
