### ISSUE TITLE
CA Ioniq 6 missing controls

### ISSUE THREAD

**Issue by MrNunu** [Hyundai-Kia-Connect/kia_uvo#735]
**Region and Brand of car**

Canada, Hyundai Ioniq 6 

**Version of the integration**

v2.14.2

**Describe the bug**

While I can set the charge limits and lock/unlock the doors, I don't have climate start/stop and start/stop charge. These options are available to me in the app. I have no other Hyundai/KIA to see if it's just my car and didn't find a similar bug. 

I also see all (I think) sensor entities. 

**Debug logs if an error occurred**

No error

**Comment by cdnninja** [comment]
In the dev menu you don't have start_climate and stop?

**Comment by MrNunu** [comment]
Oh I do. Apologies, then :)
