### ISSUE TITLE
Reload before send "start charge"

### ISSUE THREAD

**Issue by Gutein** [Hyundai-Kia-Connect/kia_uvo#738]
In HA I want to send "reload" before "start charge" 
I want to wake up the integration before sending "start charge" when I schedule the task. Is that possible? 
Best regards.

**Comment by fuatakgun** [comment]
Please explain reload more, you mean reloading the integration or reloading the fresh data from kia servers?

**Comment by Gutein** [comment]
I mean ”reloading the integration” Bets regardsPetter Hegman7 nov. 2023 kl. 11:38 skrev Fuat Akgün ***@***.***>:﻿
Please explain reload more, you mean reloading the integration or reloading the fresh data from kia servers?

**Comment by cdnninja** [comment]
I assume due to the invalid id item.  This should be solved.  Check out #672.

**Comment by Gutein** [comment]
Great! Thanks. Keep up the good work.I try it tomorrow.Petter Hegman10 nov. 2023 kl. 23:18 skrev cdnninja ***@***.***>:﻿
I assume due to the invalid id item.  This should be solved.  Check out #672.
