### ISSUE TITLE
Support enabling/disabling of AC on Hyundai IONIQ

### ISSUE THREAD

**Issue by andreas-bulling** [Hyundai-Kia-Connect/kia_uvo#759]
I am using the integration with a Hyundai IONIQ electric (build year 2020). I can see all the sensors/status information but I am unable to control anything, such as the AC.

Should this work/have I simply not found it yet or is that not supported?

**Comment by cdnninja** [comment]
They are service calls.  Go to the developer menu > services and search for kia_uvo.  This can be tied to buttons and automations.

**Comment by andreas-bulling** [comment]
Nice, thanks! Might be good to add this to the documentation...

**Comment by cdnninja** [comment]
It is on the home page of the GitHub readme.  Listed in the services section.
