### ISSUE TITLE
Car location is unknown

### ISSUE THREAD

**Issue by sochartgit** [Hyundai-Kia-Connect/kia_uvo#767]
I was able to get the car location with previous versions of HA and your plugin.
Since last versions of tools, location is unknown.

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/83184203/9d621bae-933a-479c-9738-7695542aaab5)

I can't find a way to get it back working. Geolocation option is checked in the tool.

**Comment by cdnninja** [comment]
Location works in the native app?

**Comment by sochartgit** [comment]
Yep


________________________________
De : cdnninja ***@***.***>
Envoyé : 23 décembre 2023 13:53
À : Hyundai-Kia-Connect/kia_uvo ***@***.***>
Cc : sochartgit ***@***.***>; Author ***@***.***>
Objet : Re: [Hyundai-Kia-Connect/kia_uvo] Car location is unknown (Issue #767)


Location works in the native app?

**Comment by sochartgit** [comment]
any update on this please ?

**Comment by cdnninja** [comment]
What year is the car and what region?  Could you provide debug logs as per readme?

**Comment by sochartgit** [comment]
IONIQ5 2022, Canada.

Logger: hyundai_kia_connect_api.KiaUvoApiCA
Source: /usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py:512
First occurred: January 8, 2024 at 10:09:52 AM (4 occurrences)
Last logged: 8:13:08 AM

hyundai_kia_connect_api - Get vehicle location failed

**Comment by Bubo08** [comment]
Could you please also provide the debug log?

**Comment by sochartgit** [comment]
Sure, can you just help me to find it in HA please ? Thanks.

**Comment by Bubo08** [comment]
You have to follow the readme of this integration: https://github.com/Hyundai-Kia-Connect/kia_uvo#troubleshooting
