### ISSUE TITLE
Kia Niro 2023 climate control missing

### ISSUE THREAD

**Issue by cazzoo** [Hyundai-Kia-Connect/kia_uvo#773]
**Region and Brand of car**
EU - Kia Niro 2023

**Version of the integration**
Latest from HACS

**Describe the bug**
I've been setting my account up and it appears I can see most of the sensors available but also some controls such lock/unlock, max charge levels but It lacks the climate start/stop feature.
I've been verifying the kia connect app and this feature is available to me and works out of the box.

**Expected behaviour**
Ability to start/stop the climate remotely from HA

**Screenshots**
![Screenshot_20231216-223622_Home_Assistant.png](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/1876754/e5e0198d-d1f4-4ae7-9df7-a58f83448152)

**Additional context**

**Comment by cdnninja** [comment]
It's a service either head to developer menu to try it or create a button and automation on a dashboard. 

Reason for this is we need input like temperature seat settings etc which can't easily be done in that view.

**Comment by cazzoo** [comment]
Oh, I just understood now how this is working. For those who ask themselves, here is the manual trigger from the developer menu:
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/1876754/a910eb0d-1064-49c9-8d4a-f82515b983a4)

Thanks highlighting it
