### ISSUE TITLE
Seat heating / Stzheizung

### ISSUE THREAD

**Issue by Stepsilein** [Hyundai-Kia-Connect/kia_uvo#779]
Hello,
great addon 👍.
A question:
At my Hyundai Ioniq5 all entities are working nice in HA.
Just one setting does't take effekt:
If I enable seat heater (left), its not switching on the seat heater.
Eveythig else like steering wheel heater and so on, is workig nice.
Is there a blocking to seat heater by remote engaging?
Thanks for Info in advance.
Bye  for now

**Comment by cdnninja** [comment]
What region?   And does it work in your native app?

**Comment by Stepsilein** [comment]
EU.
And native App isn't offering seat heating setting (as some other settings like 12V Battery), but your Addon shows this settings.
All working, but seat heating not.

Am 23. Dezember 2023 00:28:05 MEZ schrieb cdnninja ***@***.***>:

**Comment by cdnninja** [comment]
If the native app doesn't have it your car doesn't support it.

**Comment by Stepsilein** [comment]
Okay.
At the moment I can't reinstall the addon... somthing went wrong 🤷🏼‍♂️

Am 23. Dezember 2023 18:13:41 MEZ schrieb cdnninja ***@***.***>:

**Comment by LQkkeN** [comment]
> If the native app doesn't have it your car doesn't support it.  

Can you link the doc/spec where this is defined? Thanks!

**Comment by cdnninja** [comment]
It says it right at the top of our start climate function.  Unless you are asking where does Kia Hyundai document this?

**Comment by LQkkeN** [comment]
>Unless you are asking where does Kia Hyundai document this?

Yes, sorry, this was what I was asking

**Comment by Stepsilein** [comment]
As there is no context/old part of communikstion, no way to remember by myself about.
Anyway, everything okay 🙋🏼‍♂️

Am 2. Januar 2024 14:38:51 MEZ schrieb "Mathias Løkke Madsen" ***@***.***>:

**Comment by cdnninja** [comment]
> >Unless you are asking where does Kia Hyundai document this?
> 
> 
> 
> Yes, sorry, this was what I was asking

Not sure if they do.

**Comment by Stepsilein** [comment]
No, K'm sure Hyundai ist keeping ist secret.
But you made this Integration, so you know about... else where did you get those Entinities from 🤔

Am 2. Januar 2024 16:40:46 MEZ schrieb cdnninja ***@***.***>:

**Comment by cdnninja** [comment]
This is a collaboration. Much of it wasn't me.  

The traffic was sniffed and replicated from what the mobile app does.  Some cars have seats that do this others don't.  No sign exists in the sniffing of why some do some don't.

**Comment by Stepsilein** [comment]
Thank you about Info.
Yes, ist that Kia/Hyundai sharing car Platform, uses different by Manufakturer an different Models and so on.
Bye 🙋🏼‍♂️

Am 2. Januar 2024 17:12:30 MEZ schrieb cdnninja ***@***.***>:
