### ISSUE TITLE
Support for Kia EV9

### ISSUE THREAD

**Issue by carpe07** [Hyundai-Kia-Connect/kia_uvo#784]
Hi,

I have a brand new Kia EV9 ;-)
Unfortunately the HASSIO integration works very limited. I can't e.g. see the SOC of the EV battery.
Also not the charging state will not be displayed.

Any ideas?
Many thanks!
Per

**Comment by cdnninja** [comment]
Duplicate of https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/766.
