### ISSUE TITLE
Depreciated function SOURCE_TYPE_GPS 

### ISSUE THREAD

**Issue by ridderr** [Hyundai-Kia-Connect/kia_uvo#785]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Not related

**Version of the integration**
Latest  (2.18)

**Describe the bug**
Erverything is still working

**Debug logs if an error occurred**
SOURCE_TYPE_GPS was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
To confirm you are saying we have over a year to do this?  Or is that a typo?

**Comment by ridderr** [comment]
It was cut/paste, so I assume you will have a year.

**Comment by fuatakgun** [comment]
They usually spare long enough time before deprecating these enums, thanks for heads up
