### ISSUE TITLE
Not able to set preheating climate of a EV6

### ISSUE THREAD

**Issue by alexebner** [Hyundai-Kia-Connect/kia_uvo#789]
It seems that there is no possibility to enable the heating of an EV6. There is also not possible to change the temperature of the car.

![Screenshot_20231231_105608_Home Assistant](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/26386738/ef8e3825-9cc3-4a44-b80d-e15fd19b754f)

**Comment by cdnninja** [comment]
It's in the services menu.

**Comment by alexebner** [comment]
Thank you. i have found it.
