### ISSUE TITLE
Hyundai Climate Start won't change from 66 degrees

### ISSUE THREAD

**Issue by ErnieErnesto** [Hyundai-Kia-Connect/kia_uvo#792]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA and 2022 Hyundai Kona EV
**Version of the integration**
2.18.1

**Describe the bug**
Can't seem to see where to change units from metric to F. No matter what temperature I set the climate start for it defaults to 66 degrees Fahrenheit. Thanks for all your hard work on this. It's an awesome plugin!

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Any Start command

**Expected behavior**
Changing temp should change climate temp

**Screenshots**

**Additional context**
Help?

**Comment by cdnninja** [comment]
Send in F.  I believe it will only take f for USA cars.

**Comment by ErnieErnesto** [comment]
That worked! Thank you!
