### ISSUE TITLE
Kia Sportage NQ5 EU: Battery Level not available 

### ISSUE THREAD

**Issue by DeeJaWue** [Hyundai-Kia-Connect/kia_uvo#794]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Kia Sportage NQ5 T-GDI 1,6 Germany
**Version of the integration**
2.18.1

**Describe the bug**
Since 03.01.2024 the Car Betty Level isn't reported and it's not available.
No error message in the logs, HA restart doesn't help.
Anything else works normal.
I also made a restart of the Car Media System (the small button near to the volume control)

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240104_102217_Home Assistant](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/10549877/ea828cca-f02e-482e-bb50-eae564516e29)

**Additional context**

**Comment by Fonebone27** [comment]
> After a complete reinstall of this integration (delete car, delete Integration, restart HA, install integration, restart HA, connect the car) everything works fine.

Did try the same but now it's gone, can't find it anymore. 
![bilde](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/14042550/18692946-4567-48b5-9202-2444814fc19c)

**Comment by cdnninja** [comment]
Take your car for a drive and restart the integration.  


Typically this means your battery is low and the api just stops reporting the data.

**Comment by DeeJaWue** [comment]
You can close it :)
