### ISSUE TITLE
WARNING issues in HASS 2024.1 because of deprecations

### ISSUE THREAD

**Issue by stoyandim** [Hyundai-Kia-Connect/kia_uvo#796]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe Region / Santa Fe 2021
**Version of the integration**
HomeAssistant 2024.1

**Describe the bug**
Deprecation logs in HASS 2024.1

**Debug logs if an error occurred**
1)
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:204
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 13:54:22 (2 occurrences)
Last logged: 13:54:22

SOURCE_TYPE_GPS was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues
Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

2)
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 13:54:22 (4 occurrences)
Last logged: 13:54:22

TIME_MINUTES was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues
TIME_DAYS was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.DAYS instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues
ENERGY_WATT_HOUR was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues
ENERGY_KILO_WATT_HOUR was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues

**Comment by stoyandim** [comment]
From what I saw, similar to #785

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/790 resolves this.
