### ISSUE TITLE
Actual Home Assistant tells changes in names

### ISSUE THREAD

**Issue by Stepsilein** [Hyundai-Kia-Connect/kia_uvo#798]
EU Ioniq5
**Region and Brand of car**
Newest
**Version of the integration**

See two included Screens please for details.
**Describe the bug

**Screenshots** 2 included
![hint2](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/148879106/e430624a-132d-44de-a054-0cfa4e2dd002)
![hint1](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/148879106/32dd0828-e431-4c52-b76c-e89ebf080d39)

**Comment by cdnninja** [comment]
This is resolved in the master branch.

**Comment by cdnninja** [comment]
2.19 as a beta release solves this.

**Comment by Stepsilein** [comment]
Thanks.
But how to get/update the Integration to beta inside Home Assistant ?

**Comment by cdnninja** [comment]
It can be downloaded in HACS.
