### ISSUE TITLE
Cannot find sign in

### ISSUE THREAD

**Issue by ahlbergr** [Hyundai-Kia-Connect/kia_uvo#81]
Hi,

I just installed this integration through HACS, but I don't find any way to configure my account. No guides if this can be done in configuration.yaml and I cannot find the UI either. What am I missing?

![Screenshot 2021-10-11 at 08 59 06](https://user-images.githubusercontent.com/86572023/136746415-5927ee4a-6b1d-45fc-89d2-818b6f0edb20.png)

**Comment by ahlbergr** [comment]
Double face palm!!!

**Comment by mvklingeren** [comment]
Why the double face-palm, i just came here.. to find out about similar experiences.

I can't find it either via HACS.

**Comment by mvklingeren** [comment]
![Screenshot_20211011-233048_Home Assistant](https://user-images.githubusercontent.com/917997/136857953-cff2cc1d-c0e4-46a8-af28-2fb610a4022e.jpg)
