### ISSUE TITLE
12v Battery Help

### ISSUE THREAD

**Issue by sbcrumb** [Hyundai-Kia-Connect/kia_uvo#815]
**Region and Brand of car**

US/Kia

**Version of the integration**
2.19.0

Not a bug, but I need help
My car a 2023 Sorento, has been having a 12v battery drain where it has reached 12% in a 7 day period of sitting in my garage.
My refresh settings are all stock so 1440Min on the force. and the no force starting at 22 and finishing at 7.
I also have a 2023 Sportage that has none of these issues.(both on HA same settings)

I am wondering aside from HA where can I read the 12v battery readings? I don't see them in my Android App at all. Or the webpage. Is there a dev mode in the webpage I can pull them from?
Reason I am asking is it has been at the dealer for about 30 days now they have been doing various things to it. Even had the modem unit disconnected so HA or the regular app couldn't talk to the car, and the tech was able to take a reading after 3 days and saw the battery lost a 10% of charge. And today Kia Corp told the tech to have me remove the app from my phone change my password etc. As part of the troubleshooting.(yes makes no sense.)

So if someone can help me to be able to pull more data on this that would be great. I am unfortunately trying to get Kia to replace the entire car so the more info I have the better.

**Comment by Bubo08** [comment]
I had a similar problem and I can tell you, that it has nothing to do with this integration. I went the same rode and checked everything. The integration is only reading cached values.
My problem was, that the ev battery was losing power because the 12 volt battery was losing power and had to be filled up several times per hour. In the end KIA found out that they had to reset the battery controller. This solved the problem.
Could you please close this bug? If you have further questions, could you please move it to the discussion board?

**Comment by cdnninja** [comment]
The integration will do forced based on the config.  We have greatly increased the default scan for this to avoid polling the car.  Right now I think it's roughly daily.   

Vast majority of calls never wake the car up.

**Comment by sbcrumb** [comment]
Forgive me for the ask of this, reason I was trying to gather more data is the route Kia corp is taking and asking. And being I have filled a lemon lawsuit I am trying to cover my basis and not have anything outside blamed as the issue.
As I don't believe it is the HA integration cause as I said I have another KIA and same settings and it doesn't have the issues mine does with the battery.. 

And I thought there was away to read it from the webui other values so I was looking to get that is all. But yes I can close this. 
Very sorry.

**Comment by Bubo08** [comment]
I understandand and no offence taken. I wanted only to reduce the number of
bugs. You are welcome to ask any question in the discussion section.

About your question: You may consider to use an OBD2 interface. It is HW
and not SW and should therefore not affect the Battery much.

sbcrumb ***@***.***> schrieb am Fr., 2. Feb. 2024, 18:21:

**Comment by cdnninja** [comment]
I have seen reports of obd devices killing battery.  It triggers car to wake up to collect all the data.
