### ISSUE TITLE
Daily driving stats not sorted on date

### ISSUE THREAD

**Issue by jwillemsen** [Hyundai-Kia-Connect/kia_uvo#820]
**Region and Brand of car**

Kona 2024 EV EU CCS2 supported

**Version of the integration**

2.20.0

**Describe the bug**
The daily driving stats are not sorted on date, all through each other

**To Reproduce**

Check the daily driving stats, see for example the screenshot 

**Expected behavior**

Sorted on date

**Screenshots**
![Screenshot_20240205_135508](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/47353/84d25698-7bbd-4c09-b3c1-e0416be2f56d)

**Additional context**

**Comment by Bubo08** [comment]
Yes, they are really in the wrong order. But I am wondering if we should not integrate the driving history somehow into home assistant. For example, that we are exposing the last driving day. At the time we have to get it we a template, which is cumbersome.

**Comment by ZuinigeRijder** [comment]
This will probably fix this issue:  [fix: EU sort daily stats for same behaviour between cc2 and non-cc2 #498 ](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/498)

**Comment by cdnninja** [comment]
This is now in the master branch.  You can update in HACS to master or wait until the weekend release.
