### ISSUE TITLE
Include state_class: measurement into sensor.XXXXX_ev_battery_level entity

### ISSUE THREAD

**Issue by salfuman33** [Hyundai-Kia-Connect/kia_uvo#824]
**Is your feature request related to a problem? Please describe.**
I tried to add this entity to a new card into Home Assistant as I do with my other Cars or devices, but it doesnt works because there are no statistics about it.

**Describe the solution you'd like**
I have solve it modifiying the entity manualy and adding  state_class: measurement attribute to it

**Describe alternatives you've considered**
Probably the entity should have this attribute by default as the other battery level entities that I have by other devices and integrations.

**Additional context**

**Comment by cdnninja** [comment]
Are you able to create a pull request for this?  I believe quick change.

**Comment by salfuman33** [comment]
> Are you able to create a pull request for this? I believe quick change.

Sorry im not fluent in Github. I think i cant do it and yes I think its a quick change and necessary to report as other battery identities from other vendors.

**Comment by jwillemsen** [comment]
I think this one can be closed
