### ISSUE TITLE
Kia Australia - Cannot login - logs say Kia is not supported in Australia yet

### ISSUE THREAD

**Issue by hcross13** [Hyundai-Kia-Connect/kia_uvo#826]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Australia (Perth) - Kia EV9

**Version of the integration**
v2.20.2

**Describe the bug**
When entering the required details (Username, Password & Pin) and selecting the Region of Australia and the Brand of Kia, an Unexpected error occurs

The logs show that Kia is not supported in Australia yet, I'd be happy to volunteer to be a test user and contribute to the development/expansion of the integration.

**Debug logs if an error occurred**

2024-02-12 16:38:58.509 ERROR (MainThread) [custom_components.kia_uvo.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 58, in validate_input
    api = VehicleManager.get_implementation_by_region_brand(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 257, in get_implementation_by_region_brand
    return KiaUvoApiAU(region, brand, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiAU.py", line 106, in __init__
    raise APIError("Kia is not supported in Australia yet")
hyundai_kia_connect_api.exceptions.APIError: Kia is not supported in Australia yet

**To Reproduce**
Login with valid credentials and choose Region of Australia, Brand of Kia

**Expected behavior**
Able to login and see EV9 device and entities

**Screenshots**
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/4954703/2b7da961-38ab-44d0-b072-b6ce71e0e75a)

**Additional context**

**Comment by jaselynch** [comment]
I am also in Australia and seeing the same error as above. I have a Kia Niro GT-Line. Happy to assist with testing where possible.

**Comment by cdnninja** [comment]
Could you try master branch?

**Comment by jaselynch** [comment]
Working for me now in v2.22.0. Thank you!
