### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by sarathai82112** [Hyundai-Kia-Connect/kia_uvo#828]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**
2.20.1/2.20.2/20.19.1

**Describe the bug**
Update failed (File empty), new installation not possible, downloadbar runs indefintly. Other integrations can be installed

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
If HACS is failing to install this is a HACS issue.   You can also manually install if you like.

**Comment by sarathai82112** [comment]
Hi, thanks. It's very strange, some integrations can be downloaded, some can't. Problem was, I have no idea what I'm doing, since I only have HA because of the Hyundai integration. I was able to install it manually, so it is working for now, but I deactivated the auto-update. Thanks again, I will close the threat.
