### ISSUE TITLE
Enable debug logging through main HA Settings integration menu

### ISSUE THREAD

**Issue by Taomyn** [Hyundai-Kia-Connect/kia_uvo#829]
**Is your feature request related to a problem? Please describe.**
Enabling debug logging requires editing a config file then restarting HA, then capturing the log data manually.

**Describe the solution you'd like**
HA allows the enable/disable of debug logging from within the integration options under the main HA settings, this makes it simpler for everyone to provide logs for issues or other requests, and works immediately.

**Additional context**
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/4365929/501604c5-39bf-4722-a99c-e07bfe977d44)

At the moment the switch only enables just a few messages, but nothing useful

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/4365929/d102cb25-164a-47a2-9f62-aae6e13bd172)

When you disable debug logging, the log file is offered as a download which you can then edit/trim as necessary.

**Comment by cdnninja** [comment]
Are you able to test this PR out locally to confirm it solves what you would like?  I don't own a Kia anymore so can't test. 

#830

**Comment by Taomyn** [comment]
> Are you able to test this PR out locally to confirm it solves what you would like? I don't own a Kia anymore so can't test.
> 
> #830

I uploaded the changed json file to replace the current one, restarted HA and tested. Worked perfectly and didn't need to restart HA to toggle debugging, many thanks. This will make it much easier to quickly check things when there's a problem.

**Comment by cdnninja** [comment]
Awesome. It's merged for next release.
