### ISSUE TITLE
Typo in configuration - force refresh description

### ISSUE THREAD

**Issue by madopal** [Hyundai-Kia-Connect/kia_uvo#833]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Kia EV6/Niro, but irrelevant here

**Version of the integration**
Current tip of master

**Describe the bug**
Description says "use cation setting this too low", should be "caution"

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot from 2024-02-17 09-12-10](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/250266/b6c13c1a-5db1-4303-b7a6-f8c65105b1ae)

**Additional context**

**Comment by madopal** [comment]
BTW, it's a simple fix, but I have a branch. Also, as a dev, I'd love to contribute. I have 2 EVs, and I'd be happy to be other eyes on this.

**Comment by fuatakgun** [comment]
All types of contribution are more than welcome

**Comment by madopal** [comment]
Can I get added as a contributor? It says I don't have permissions to create a branch when I try and push a new branch.

**Comment by cdnninja** [comment]
You can create a pull from your own branch. Doesn't need to be a branch within the repo.
