### ISSUE TITLE
Fuel level reports 0% since the latest update

### ISSUE THREAD

**Issue by icovelev** [Hyundai-Kia-Connect/kia_uvo#835]
After the latest update the fuel level reports 0% 

![IMG_2331](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/31531311/c14e9b81-72af-4a07-8b51-81e58e9c3acd)

**Comment by cdnninja** [comment]
Region? Version you came from?

**Comment by icovelev** [comment]
Region: Europe
Previous version: v2.20.2
Current version: v2.21.0

**Comment by cdnninja** [comment]
To confirm when you role back it works?

**Comment by icovelev** [comment]
Tried rolling back today, but the issue persist. So most probably something in the API changed.

**Comment by cdnninja** [comment]
Go into the "data" sensor and look at the attributes.  That's the raw api. See if you can find the correct fuel data.

**Comment by icovelev** [comment]
It’s showing zero there as well. Is there a possibility that they have removed these as an attribute?

fuellevel: 0

**Comment by cdnninja** [comment]
Does your native app show correctly?

**Comment by icovelev** [comment]
Yes.

**Comment by fuatakgun** [comment]
Please check the debug sensor attributes if there exists fuel data. If not, it means it is not returned by api.

**Comment by cdnninja** [comment]
If native app works something is up here.  

This could be the new car support impacting this.

**Comment by icovelev** [comment]
Out of the blue is working back again. The car is 2023 Tucson Hybrid. Maybe they were changing something in the API. Will see if it will stop working again.
![IMG_2332](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/31531311/2dff3794-6eed-40ae-86ba-84b38a1ed3d5)
