### ISSUE TITLE
KeyError: 'calculativeOdo' since latest update

### ISSUE THREAD

**Issue by ridderr** [Hyundai-Kia-Connect/kia_uvo#842]
**Region and Brand of car**
KIA Sportage - Europe

**Version of the integration**
V2.22.0

**Describe the bug**
There are bugs reported in the log (see below)

**Debug logs if an error occurred**
```
Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: /usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py:362
First occurred: 17:04:54 (4 occurrences)
Last logged: 19:05:27

Failed to parse driving info. Possible reasons: - incompatible vehicle (ICE) - new API format - API outage
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 357, in update_vehicle_with_cached_state
    state = self._get_driving_info(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1382, in _get_driving_info
    and drivingInfoItem["calculativeOdo"] > 0
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'calculativeOdo'
```

**To Reproduce**
Reported after each update with data from car

**Comment by cdnninja** [comment]
What year of car? Is it a phev?

**Comment by ridderr** [comment]
Car build 2023 and it is a phev

**Comment by cdnninja** [comment]
Does native app show driving stats?

**Comment by ridderr** [comment]
Is this what you're looking for? 
![Screenshot_20240226_210424_Kia Connect](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/12719238/7b57f214-d2d5-4a88-b6e5-56f7a8131469)

**Comment by cazzoo** [comment]
I have the same error in HA with a Kia xCeed PHEV 2020

**Comment by pdcleyn** [comment]
+1

**Comment by elden1337** [comment]
pr for eu-api published ^

**Comment by elden1337** [comment]
should be fine now @ridderr if you update to latest. please check and verify.
