### ISSUE TITLE
EV9 charging control

### ISSUE THREAD

**Issue by stintov** [Hyundai-Kia-Connect/kia_uvo#849]
Hi, 

Please can I request a way to start and stop charging from the integration.

the help points to a page that no longer exists on GitHub. 

Currently unable to build any automations

**Comment by cdnninja** [comment]
Check services in the dev menu.

**Comment by stintov** [comment]
Hi, thanks for responding. What exactly am I looking for in services please?

**Comment by cdnninja** [comment]
This is covered in the read me.

**Comment by stintov** [comment]
Thanks, I’m new to HA and didn't even know services were a thing, so thanks for showing me where to look.

None of the services mentioned are listed for me.

Can you offer any advice for me please?

**Comment by cdnninja** [comment]
To confirm dev menu services have no kia_uvo items? Please provide a screenshot.

**Comment by stintov** [comment]
My apologies, I thought I had replied back to say I found the states. Thanks for signposting me. The only issue I’m left with is there is no charging indicator on EV9 and also states keep going unknown.

Warm Regards

Austin Tovey
07917 418530
________________________________
