### ISSUE TITLE
Sensors are unavailable since 2.24.1

### ISSUE THREAD

**Issue by JordanM1738** [Hyundai-Kia-Connect/kia_uvo#858]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada Hyundai

**Version of the integration**
2.24.1

**Describe the bug**
Lots of sensors are unavailable since 2.24.1.
Battery, Fuel, Odometer

**Debug logs if an error occurred**
Enregistreur: homeassistant.components.sensor
Source: helpers/entity_platform.py:350
intégration: Capteur (documentation, problèmes)
S'est produit pour la première fois: 12:45:10 (1 occurrences)
Dernier enregistrement: 12:45:10

Error while setting up kia_uvo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/kia_uvo/sensor.py", line 261, in async_setup_entry
    if self.vehicle.daily_stats:
       ^^^^
NameError: name 'self' is not defined

**To Reproduce**
Install 2.24.1, 2.24.0 works fine

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JordanM1738** [comment]
it works fine with 2.24.2
Thanks

**Comment by mikejward** [comment]
I think it's related to this but there seems to be one missing from my Niro EV too - "sensor.niro_monthly_energy_consumption" as my dashboard is showing it as unavailable now.

Region and Brand of car
Europe Kia

Version of the integration
2.24.2

Apologies if this is wrong - never reported an issue before. Go easy on me

**Comment by cdnninja** [comment]
Unless all unavailable that's a different issue.  Please create and issue and post logs for that.
