### ISSUE TITLE
EU Hyundai doesn't  report 12v battery status

### ISSUE THREAD

**Issue by salfuman33** [Hyundai-Kia-Connect/kia_uvo#871]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**
v2.24.2

**Describe the bug**
12v Battery % status appears stuck. If you reconfigure the integration, the entity dissapear.

**To Reproduce**
Nothing needed.

**Expected behavior**
12v Battery % appears as entity

**Screenshots**

**Additional context**
This entity its very usefull to avoid "zombie mode" on Ionic 5 vehicule and now its not available.

**Comment by salfuman33** [comment]
I read in another mate post that after a 12v battery he loose the status too. I just have a 12v batter fail yesterday, so may be its the same case. May be the problem is not that the integration fails, may be the car its not given info about battery status ¿?¿?

**Comment by salfuman33** [comment]
Update:
The problem seems to be a Car problem and not an integration problem.
When the car batery "die", stop reporting battery info. I have reset the car (disconnect the battery and connect it again) and it reports battery status again...but after a while it fails again. So it is not a Bug.

**Comment by kevin-hill** [comment]
Our Hyundai Ioniq 6 went in for a rather long (7-week) repair to a workshop in the UK and now the 12v battery entity says it is no longer provided by the integration. AFAIK, no firmware updates have been applied to the car over that time, so it would seem to either be an integration issue or something related to the car. I might trying disconnecting then reconnecting the 12v battery, but won’t that have some impact on the car setup etc.?

**Comment by salfuman33** [comment]
> Our Hyundai Ioniq 6 went in for a rather long (7-week) repair to a workshop in the UK and now the 12v battery entity says it is no longer provided by the integration. AFAIK, no firmware updates have been applied to the car over that time, so it would seem to either be an integration issue or something related to the car. I might trying disconnecting then reconnecting the 12v battery, but won’t that have some impact on the car setup etc.?

Hi Kevin,
As far as I know this process doesnt have impact for the car. One of the times I do it I let the car without battery along five minutes and no one error, preference or configuration missing.

The battery info into the integration take a long time to appear again, so have a little patien after do this process...and reload the integration. In one time, the battery info doesnt appear until I do it and take a little trip with the car.

Regards.
