### ISSUE TITLE
Stop charge acts like a toggle

### ISSUE THREAD

**Issue by JeremyMahieu** [Hyundai-Kia-Connect/kia_uvo#875]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU, Kia

**Version of the integration**
2.24.2

**Describe the bug**
I use the home assistant services through node-RED. When I do a "stop charging" command, while the car is already stopped charging, it starts charging instead.

**To Reproduce**
Send a stop charge while the car is already not charging.

**Expected behavior**
When sending a stop charge, while the car is not charging it should not do anything. It shouldn't behave as a toggle.

**Screenshots**
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/23409814/1392f310-2547-4aa0-979c-5dcc2d0bf626)

**Comment by cdnninja** [comment]
No logic exists to make this a toggle.  If you are getting that behaviour I would think the api is ignoring what we pass and acting like a toggle.  I assume native app would have the same bug.

**Comment by JeremyMahieu** [comment]
Correct the OEM Kia Connect app has the same problem. I don't think it should be fixed in this library, you can probably close the issue then.
