### ISSUE TITLE
Blue link login failed

### ISSUE THREAD

**Issue by JoshuaSeidel** [Hyundai-Kia-Connect/kia_uvo#877]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
2019 Hyundai Tucson
**Version of the integration**
Latest

**Describe the bug**
I'm already logged in with this integration to my Kia, I'm now adding my wife's Hyundai as a separate hub but it keeps saying login failed in logs, but when I login to the app with the same username and password it works fine 
**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Logs and region?

**Comment by estiens** [comment]
Failing here as well with Hyundai USA (with or without PIN)

looks like it isn't getting a token back in the response, but doesn't log what the response is

  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 125, in login
    access_token = response["access_token"]
                   ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

**Comment by estiens** [comment]
I got this to work by simply resetting my password and changing it (although I could log in fine to the app) and then I could log in with new password. Little turn off and turn on trick

**Comment by cdnninja** [comment]
Going to close as OP didn't respond and sounds like you were able to solve this.
