### ISSUE TITLE
Forced update function doesn't seem to actually force update

### ISSUE THREAD

**Issue by jayscovill** [Hyundai-Kia-Connect/kia_uvo#879]
This is more of a question than a bug report.  I couldn't find any other posts about this.  Has anyone else experienced the behaviour where the forced update interval for the integration doesn't seem to actually do anything?  I have mine set to 90 minutes for testing right now and the charge status, batter levels, etc are never up to date until I manually call the forced update service.

If I manually update the vehicle status in the Kia Connect app I see the up-to-date data so the car is definitely sending to the cloud.  So really it looks like neither the forced update or cached data read are doing anything.

I have debug logging turned but don't see any log entries for the integration that indicate it's even trying to force update on that schedule.

**Comment by cdnninja** [comment]
It isn't force update at that interval but rather if no updates since that it will force on next scan.

**Comment by jayscovill** [comment]
But even the cached scans aren't updating even though they are server side, from my experience anyways. No worries, will just disable the integration force update and schedule my own with an automation.

Also noticed that the "EV Range" is the same as the "Total Driving Range" for my 2024 Sportage PHEV.  But will file a separate bug report for that.

Cheers

**Comment by cdnninja** [comment]
Items from the issue template like logs will be needed to confirm what's going on. 

What's your regular scan interval set to?

**Comment by jayscovill** [comment]
Does enabling debug logging from the UI suffice or do I need to mod configuration.yaml?  I've enabled it in the UI and restarted HASS but don't seem to get much in the logs related to the integration.

Scan interval is set to 15 minutes for testing.  Forced update is set to 90 minutes

**Comment by cdnninja** [comment]
Yes interface is fine.   When you say not much nots do you mean none?   Sometimes using interface I find it turns off the switch after a bit for debug logs.

**Comment by jayscovill** [comment]
I figured out what I was doing wrong.  Can now get the log entries.  I'll close this off since I'm working around with scheduled forced updates.
