### ISSUE TITLE
Installation of the integration failed - 500 Internal Server Error Server - API release note change from 3.19.1 to 3.20.1

### ISSUE THREAD

**Issue by Schnullerbacke2** [Hyundai-Kia-Connect/kia_uvo#882]
**Region and Brand of car**
EU/Germany Hyundai Ioniq 5

**Version of the integration**
v.2.24.3

**Describe the bug**
The installation of the integration is answered with following message "Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble"
Probably related to the API release note change from 3.19.1 to 3.20.1.

**Debug logs if an error occurred**
Unable to install package hyundai_kia_connect_api==3.20.1: ERROR: Could not find a version that satisfies the requirement hyundai_kia_connect_api==3.20.1 ... ERROR: No matching distribution found for hyundai_kia_connect_api==3.20.1

homeassistant.requirements.RequirementsNotFound: Requirements for kia_uvo not found: ['hyundai_kia_connect_api==3.20.1'].

**Screenshots**
![Error](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/51903069/61329f30-3c90-454f-adca-dbfba5c48dda)
![API release note change from 3 19 1 to 3 20 1](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/51903069/30b3c841-66bc-440d-baa9-97fb24df3d5f)

**Comment by cdnninja** [comment]
Pulled the release. pypi didn't publish the package. Once fixed will rerelease.

**Comment by cdnninja** [comment]
This should be solved.  Please try latest.

**Comment by Schnullerbacke2** [comment]
Perfect, got it installed.
Thx al lot for quick response.
