### ISSUE TITLE
SSL Cert Function error, integration data unavailable

### ISSUE THREAD

**Issue by graymccord** [Hyundai-Kia-Connect/kia_uvo#888]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
US / Hyundai Ioniq 5
**Version of the integration**
2.24.4

**Describe the bug**
Was working up until a couple of days ago, then started showing as unavailable. Tried restarting HA, checked for updates, etc. with no change
**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
install and start integration

**Expected behavior**
should connect and provide data
**Screenshots**
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/124184741/34deadb7-69a3-45bb-9d9e-cd4790807e8c)

**Additional context**
Bluelink disconnected on my phone at about the same time this happened, I was able to reconnect using the old credentials, although I believe it asked for 2FA (email ed code)

**Comment by cdnninja** [comment]
Please update to latest.
