### ISSUE TITLE
Ability to change the existing PIN provided

### ISSUE THREAD

**Issue by dbolger** [Hyundai-Kia-Connect/kia_uvo#890]
**Is your feature request related to a problem? Please describe.**
I recently forgot my PIN so I was required to reset it in the Bluelink app. Now that its reset, the only way I can change the PIN would be to reconfigure the vehicle in Home Assistant, which will result in data loss.

**Describe the solution you'd like**
The ability to change a PIN for a configured vehicle.

**Comment by cdnninja** [comment]
Config in the raw text files is probably best bet right now.

**Comment by dbolger** [comment]
Where are the raw text files? @cdnninja

**Comment by cdnninja** [comment]
Not sure the exact path. They are the core configuration files for home assistant.   Need to be very careful with them.

**Comment by dbolger** [comment]
Would you be able to find it? My BlueLink PIN keeps getting locked due to the incorrect PIN queries from HA.

**Comment by cdnninja** [comment]
https://community.home-assistant.io/t/integration-configuration-files/76040/3
