### ISSUE TITLE
since a week my Homeassistant dont connect to my EV6

### ISSUE THREAD

**Issue by higgy-de** [Hyundai-Kia-Connect/kia_uvo#901]
Hello,
since a week my Homeassistant dont connect to my EV6.

Dont know how to search the problem ... who can help me ?

EU , Kia EV6 

**Version of the integration**
2.25

**Describe the bug**
see picture

![Zwischenablage05](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/158240781/0b5319d4-edff-4ac5-820c-c67815893181)

**Comment by higgy-de** [comment]
just came  2.25.1 ... looks like it had connected again ?! :)

**Comment by cdnninja** [comment]
So this started yesterday? If so yes but existed in a release.   Can we close this?

**Comment by higgy-de** [comment]
Yes, I thinks so ...when this problem comes back, i will start a new one :) tnx
