### ISSUE TITLE
Hunday Tucson 2023 pre warm and climate features

### ISSUE THREAD

**Issue by ewookscorp** [Hyundai-Kia-Connect/kia_uvo#908]
Is it possible to get Hunday Tucson 2023 pre warming and climate functions and timer works via HomeAssistant in EU area?

**Comment by cdnninja** [comment]
What is the error when you try to do it?

**Comment by ewookscorp** [comment]
No any error, not give even any options to start climate or pre heat.  Only Unlock/lock door is available. Status of climate is coming ok. 
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/555283/ba5d2003-26b4-482f-8d56-904d6b46604c)

**Comment by cdnninja** [comment]
Go into developers service menu as per the readme.

**Comment by TheMoonMan00** [comment]
> Go into developers service menu as per the readme.

So, where is this developers service menu? It’s kind of cryptic this way.

**Comment by cdnninja** [comment]
https://www.home-assistant.io/docs/tools/dev-tools/
