### ISSUE TITLE
Missing 12V car battery level

### ISSUE THREAD

**Issue by nord-** [Hyundai-Kia-Connect/kia_uvo#915]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe EV6

**Version of the integration**
2.26.1

**Describe the bug**
Since I updated to latest version I no longer see the 12V-battery SoC. (`sensor.ev6_car_battery_level`)
"This entity is no longer being provided by the kia_uvo integration. If the entity is no longer in use, delete it in settings."

**Screenshots**
![bild](https://github.com/user-attachments/assets/7da1ae78-ac54-4bd3-b47b-e8236645e7d8)
![bild](https://github.com/user-attachments/assets/310837de-3461-4e6f-babb-d2bc3932040c)

**Comment by Boertie310** [comment]
I also have this with the kia niro, it used to work.

**Comment by cdnninja** [comment]
Is the battery dead in the car?

**Comment by nord-** [comment]
> Is the battery dead in the car?

Yes, the battery broke after this.

**Comment by nord-** [comment]
It seems that after you disconnect the 12V-battery it takes a couple of days before this sensor starts working again. 

Closing the issue since it looks like a KIA problem and not with the integration.
