### ISSUE TITLE
Latest released introduce api 3.22.4

### ISSUE THREAD

**Issue by yannpub** [Hyundai-Kia-Connect/kia_uvo#921]
Integration is not starting since last version (2.26.3) 👍 ogger: homeassistant.util.package
Source: util/package.py:123
First occurred: 11:38:43 AM (3 occurrences)
Last logged: 11:38:47 AM
Unable to install package hyundai_kia_connect_api==3.22.4: ERROR: Could not find a version that satisfies the requirement hyundai_kia_connect_api==3.22.4 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.8.2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.12.0, 1.12.1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.17.1, 1.17.3, 1.18.7, 1.18.8, 1.18.10, 1.18.11, 1.18.12, 1.18.13, 1.18.14, 1.18.15, 1.18.16, 1.18.17, 1.18.18, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.19.6, 1.19.7, 1.19.8, 1.19.9, 1.19.10, 1.20.0, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.21.7, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.22.5, 1.22.6, 1.22.7, 1.22.8, 1.22.9, 1.23.0, 1.23.1, 1.24.0, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.26.5, 1.27.0, 1.27.1, 1.28.0, 1.28.1, 1.28.2, 1.28.3, 1.28.4, 1.28.5, 1.29.0, 1.29.1, 1.29.2, 1.29.3, 1.30.0, 1.31.0, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.34.5, 1.34.6, 1.34.7, 1.34.8, 1.34.9, 1.35.0, 1.35.1, 1.35.2, 1.35.3, 1.35.4, 1.35.5, 1.36.0, 1.36.1, 1.36.2, 1.36.3, 1.36.4, 1.36.5, 1.36.6, 1.36.7, 1.36.8, 1.36.9, 1.36.10, 1.36.11, 1.36.12, 1.37.0, 1.37.1, 1.37.2, 1.37.3, 1.37.4, 1.37.5, 1.37.6, 1.37.7, 1.37.8, 1.37.9, 1.37.10, 1.38.0, 1.39.0, 1.39.1, 1.39.2, 1.39.3, 1.39.4, 1.39.5, 1.39.6, 1.39.7, 1.40.0, 1.40.1, 1.40.2, 1.40.3, 1.40.4, 1.40.5, 1.40.6, 1.40.7, 1.40.8, 1.40.9, 1.40.10, 1.40.11, 1.40.12, 1.40.13, 1.41.0, 1.41.1, 1.41.2, 1.41.3, 1.41.4, 1.42.0, 1.42.1, 1.42.2, 1.42.3, 1.42.4, 1.42.5, 1.43.0, 1.43.1, 1.43.2, 1.43.3, 1.44.0, 1.44.1, 1.44.2, 1.44.3, 1.44.4, 1.45.0, 1.45.1, 1.45.2, 1.45.3, 1.45.4, 1.45.5, 1.45.6, 1.46.0, 1.47.0, 1.47.1, 1.47.2, 1.47.3, 1.50.3, 1.51.0, 1.51.1, 1.52.0, 1.52.1, 1.52.2, 1.52.3, 1.52.4, 1.52.5, 1.52.6, 1.52.7, 1.52.8, 1.52.9, 1.52.10, 1.52.11, 1.52.12, 1.52.13, 1.53.0, 1.53.1, 1.53.2, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.1.10, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.9.0, 3.9.1, 3.10.0, 3.10.1, 3.10.2, 3.10.3, 3.10.4, 3.10.5, 3.10.6, 3.10.7, 3.10.8, 3.10.9, 3.10.10, 3.10.11, 3.10.12, 3.11.0, 3.11.1, 3.11.2, 3.11.3, 3.11.4, 3.12.0, 3.13.0, 3.13.1, 3.13.2, 3.14.0, 3.14.1, 3.14.2, 3.14.3, 3.15.0, 3.15.1, 3.16.0, 3.17.0, 3.17.1, 3.17.2, 3.17.3, 3.17.4, 3.17.5, 3.17.6, 3.17.7, 3.17.8, 3.17.9, 3.17.10, 3.18.0, 3.19.0, 3.19.1, 3.20.2, 3.20.3, 3.20.5, 3.20.6, 3.20.7, 3.21.0, 3.21.1, 3.22.0, 3.22.1, 3.22.2, 3.22.3) ERROR: No matching distribution found for hyundai_kia_connect_api==3.22.4

Kia Server, Europe.

**Comment by springflake1337** [comment]
Yup, Same here in Germany.

**Comment by cy-bertrand** [comment]
2024-08-16 10:16:04.762 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'kia_uvo': Requirements for kia_uvo not found: ['hyundai_kia_connect_api==3.22.4'].

**Comment by putteg** [comment]
Same error in Sweden.

**Comment by zap-o-post** [comment]
Same here.
Downgrade to 2.26.2 work

**Comment by bjkluft** [comment]
Similar here in The Netherlands:

2024-08-16 11:39:14.448 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kia_uvo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-16 11:39:41.704 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'kia_uvo': Requirements for kia_uvo not found: ['hyundai_kia_connect_api==3.22.4'].

**Comment by terppatyyppi** [comment]
Same issue here, just updated to newest and does not load anymore. In Finland. 
Same error.

**Comment by bjkluft** [comment]
For now I changed the following (effectively going back to 2.26.2):

![image](https://github.com/user-attachments/assets/46965d1f-1f16-4300-ac79-e0038e2a5976)

**Comment by paifre** [comment]
Same issue.
New to HA, anyone to detail how to downgrade after changing the manifest.json ? Disable/Enable the integration ? Thx

**Comment by terppatyyppi** [comment]
> Same issue.
> 
> New to HA, anyone to detail how to downgrade after changing the manifest.json ? Disable/Enable the integration ? Thx

At least HA restart works.

**Comment by Ulrar** [comment]
You can just install the previous version back through HACS instead

**Comment by Smooth1337** [comment]
> You can just install the previous version back through HACS instead

Thank you. Back at v2.26.1. Working again.

**Comment by cdnninja** [comment]
I pulled the release until it is fixed.

**Comment by cdnninja** [comment]
Should now be fixed.
