### ISSUE TITLE
Failed Setup

### ISSUE THREAD

**Issue by tlorek** [Hyundai-Kia-Connect/kia_uvo#927]
Don’t see this reported, but after creating a new hub, I get the following error:

Failed setup, will retry: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.

Chose a USA based Hyundai, entered my credentials and PIN properly. 

Deleted credentials and retried without success. 

Version 2.26.6

**Comment by cdnninja** [comment]
Does the native app work right now?

**Comment by tlorek** [comment]
Yes the Hyundai app is working for our ‘24.  I do have an older Hyundai on that account that no longer connects due to 3G termination. Could that vehicle cause an issue?

**Comment by cdnninja** [comment]
Yes I wouldn't doubt it.   Would need to remove that car.

**Comment by tlorek** [comment]
That did the trick. Bottom line, older Hyundai / Kia models that used 3G need to be removed from the account.
