### ISSUE TITLE
Setting EV Off Peak Start and end times for charging

### ISSUE THREAD

**Issue by Prodec-** [Hyundai-Kia-Connect/kia_uvo#928]
Hi, 

Would it be possible to add support for setting EV Off Peak charging times? 

The times can be set via Kia connect app, so there appsrently is API for it.

My use case for the feature is that when next day's electricity prices are published in Nord Pool, I would calculate the cheapest 6 hours before next morning and send the charging time frame to my EV6. -> charging would be scheduled to the cheapest hours.

**Comment by HarriVa** [comment]
I have the same problem.

Kia EV6 (EU) randomly forgets/clears its scheduled charging schedule after a few days and immediately starts charging when it is connected to charger. I'd like to take advantage of cheaper electricity hours, but this forgetting/clearing makes it difficult.

I noticed that hyundai_kia_connect_api/KiaUvoApiEU.py has a definition for "schedule_charging_and_climate", which could solve the problem, if that would be available as a service. I could then e.g. once a day send a new charging schedule to the car.

So, would it be possible to have a service for setting up the scheduled charging? I'm unfortunately myself not familiar enough with coding to try/make this myself.
