### ISSUE TITLE
Remote Start for Kia Telluride

### ISSUE THREAD

**Issue by cmerkle** [Hyundai-Kia-Connect/kia_uvo#930]
I connected my 2024 Kia Telluride to Home Assistant using this integration, however the only control I see is to lock and unlock doors. There is no possibility to remote start the engine or start the climate control. Is it possible to add this functionality? The docs seem to indicate that it should already be able to do this.

**Comment by cmerkle** [comment]
@cdnninja Wow I'm an idiot. That's amazing, thank you!

**Comment by LiveForToday** [comment]
So I have a 2024 Hyundai Santa Fe. I would like to remote start the engine. Is this possible? I see the climate start and stop but not the actual engine. May not be possible so thought I'd ask in here. thanks...

**Comment by fuatakgun** [comment]
climate_start and climate_stop should initiate the engine right?

By the way, this integration is just limited what you can get out of respective mobile app, if the functionality does not exists, it will probabaly not work here

**Comment by LiveForToday** [comment]
> climate_start and climate_stop should initiate the engine right?
> 
> By the way, this integration is just limited what you can get out of respective mobile app, if the functionality does not exists, it will probabaly not work here

Ok I tried that. I will try again and see if it "wakes up" at all. The app can do it for sure. It is a hybrid but I don't think that should matter. Also I don't think I've said thank you for the work done here. It's awesome and I truly appreciate it very much.

**Comment by LiveForToday** [comment]
Ok I will learn to dig into the logs a bit more first. I see my PIN is wrong :). I will reconfigure although would it be possible to add the option to enter username / password / PIN in the configure by chance?
