### ISSUE TITLE
since today 15:51 no connect ... "initialisiere"

### ISSUE THREAD

**Issue by higgy-de** [Hyundai-Kia-Connect/kia_uvo#932]
Hello,
Version  2.26.6

Since today 15:51 i cannot connect the HA Kia  ... " initialisiere"  ... nothing ?!
after some time : 

Einrichtung fehlgeschlagen, wird erneut versucht: Config Not Ready: 'redirectUrl'

Anybody else also ?

**Comment by higgy-de** [comment]
and now :  

Einrichtung fehlgeschlagen, wird erneut versucht: Config Not Ready: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by DandeMC** [comment]
Same problem here. Both from germany.

**Comment by cdnninja** [comment]
Does the native app work?

**Comment by icovelev** [comment]
Same here. Europe servers, Bulgaria. The native app works without any issues.

**Comment by JonasPed** [comment]
Same problem here from Denmaek. I tried to sign out of the native app and no longer able to sign in through the native app.

**Comment by higgy-de** [comment]
IOS App is working , no problem

**Comment by MichaelMKKelly** [comment]
same issue in the UK

quick look at the logs and looks like its a login issue of some sort.

`2024-09-16 19:51:22.313 DEBUG (SyncWorker_36) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Sign In Response: {'errId': '98a1f60e-c60d-470c-834a-1d7dd8e52096', 'errCode': '4003', 'errMsg': 'Invalid values'}`

**Comment by fuatakgun** [comment]
couple of days ago, they were some updates and probably changed the login implementation again to block us

**Comment by Steven77nl** [comment]
Same issues here, from NL.
The IOS App stopped working when I did a logoff and tried to login again.
Stuck on login now on the IOS app now.
Both looks related to the login process.

**Comment by roosenbrug** [comment]
Same problem here from the Netherlands. I have the Android app, but I'll leave it logged in for now.

**Comment by JonasPed** [comment]
Looks like that as a part of the login flow there is a redirect to https://prd.eu-ccapi.kia.com:8080/api/v1/user/integration/redirect/login?user_id=<user_id>>&locale=en&state=<state>>&session_state=<session_state>. The call does not complete with success. It completes after a few minutes with an internal server error. This could indicate an issue at the Kia servers. 

It by the way looks like a standard OIDC login flow. 

I think it is time to get some sleep and check if it works tomorrow :-)

**Comment by LuckyTriple7** [comment]
Im from Germany, same Problem. Android App is working fine.

**Comment by steps56** [comment]
Same at my setup (Germany, Hyundai, Home Assistant).
App is working nice.
New configuration of the integration ends up in loop too... sadly.
Using a backup from last night also doesn't work.
I guess too its made by Hyundai Server...

**Comment by distanzcheck** [comment]
Bei mir das gleiche.

**Comment by geofflove** [comment]
Same here in uk. Was working fine for my Hyundai. Did a HA core update and restarted HA tonight and this integration is stuck on 'initialising'.

**Comment by distanzcheck** [comment]
Correct, the problem started after the Core 2024.9.2 update and subsequent restart.

**Comment by steps56** [comment]
> Correct, the problem started after the Core 2024.9.2 update and subsequent restart.

I used a backup bevore core update = no change, same problem.
I also run a 2. HA at 2. Place, without core update.
Same problem as soon as Integration restarts, or HA or ... no more working Integration/login.

Seems to be nothing rooting from that core update.

**Comment by Triple-S** [comment]
It seems that there is an issue with the Login-Servers. As long as you are logged in in either the integration or the official app everything works. So it was caused only indirectly by the cor update because after that HA restarts and because of the server issue the integration was not able to log back in.

**Comment by steps56** [comment]
I wrote at the Bluelink support some mintes ago:

![Screenshot_20240916_231819_K-9 Mail](https://github.com/user-attachments/assets/eca4bb61-96c9-4637-a018-82ef37de649b)

**Comment by ippo112** [comment]
same problem from Italy, I have HA 2024.8.3

**Comment by RuneNyhuus** [comment]
Same issue in Denmark..

**Comment by markpoirters** [comment]
Same issue in NL since 16-9

**Comment by fkieber** [comment]
Same problem in France.
I don't know if it's related, but my 12v battery discharged at the same time.
![Screenshot_20240916-193656](https://github.com/user-attachments/assets/01baa2aa-a5ef-4b6a-834c-8fbcf91375c5)

**Comment by Steven77nl** [comment]
I agree it has nothing to do with HA or the integration. For me also it started after a reboot needed for installing another integration. But the IOS App was still working fine at this point, so my first though was that I messed up something in the config.

I reverted everything back, but still had the initializing problem. Seeing the debug logs I finally came to the conclusion it must be an issue with the login process.

So testing that theory, I forced a logoff on the IOS App and tried to login again, which failed. This means as long as you have a valid logon token, you are fine. As soon as you need to request a new one, it will fail. So this is why the HA Integration starts failing after 'any' restart, no matter if you upgraded your HA, changed a integration or just did a reboot for reloading your config.

Problem will need to be fixed at the Hyundai/Kia Server side.

**Comment by walter-ve** [comment]
Noticed an hour ago the sensors were not updating for 11 hours.  
I just upgraded the KIA integration to last version and rebooted HA; it works again nicely.

**Comment by FlyHigh-Swe** [comment]
The integration is now working for me again. I had the same issue as above (lost connection after a restart related to other integrations). I also lsot connection with the Android app after login out. Both the app and the integration works as expected now.

**Comment by Art3Ska** [comment]
Yes, I confirm, now it is working correctly! So, I had to be some issue on Kia/Hyundai servers' side.

**Comment by ippo112** [comment]
now it's ok

**Comment by steps56** [comment]
As we assumed, it was a hyundai server problem.
I got some answer this morning:

![Screenshot_20240917_121818_K-9 Mail](https://github.com/user-attachments/assets/ed58dd18-dc56-40ea-ae9d-fc6156b309db)

**Comment by markpoirters** [comment]
working here also 👍

**Comment by LiveForToday** [comment]
Hello. I have a Hyundai in the USA. I'm still seeing this. I've signed out of the app on my mobile without issue. I have restarted HA a couple of times now. I do not see an update available. Is there something else I need to get this working again? Thanks.

**Comment by steps56** [comment]
> Hello. I have a Hyundai in the USA. I'm still seeing this. I've signed out of the app on my mobile without issue. I have restarted HA a couple of times now. I do not see an update available. Is there something else I need to get this working again? Thanks.

Did you set your 4digit pin at the configuration again ?

**Comment by LiveForToday** [comment]
> > Hello. I have a Hyundai in the USA. I'm still seeing this. I've signed out of the app on my mobile without issue. I have restarted HA a couple of times now. I do not see an update available. Is there something else I need to get this working again? Thanks.
> 
> Did you set your 4digit pin at the configuration again ?

I do not have the option when I click configure. Perhaps I'm just missing something? I did not remove the configuration. I am only reloading and or restarting HA.
![Hyundai_Integration](https://github.com/user-attachments/assets/14dc9721-0f68-4924-a496-48a1e133e58d)
