### ISSUE TITLE
Hyundai USA - Failed Setup will retry

### ISSUE THREAD

**Issue by LiveForToday** [Hyundai-Kia-Connect/kia_uvo#933]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
USA Hyundai
**Version of the integration**
2.26.6

**Describe the bug**
I put in the configuration.yaml and went to system > logs. Not sure if those are the proper steps but my integration stopped working yesterday. I did upgrade to the latest HA but was not sure it was related so filing a bug. Surprise others aren't seeing it. 

**Debug logs if an error occurred**
This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:135
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 4:06:36 PM (3 occurrences)
Last logged: 4:07:05 PM

Cached update failed: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 115, in check_and_force_update_vehicles self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 474, in update_vehicle_with_cached_state state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 169, in _get_vehicle_status status = dict(response["vehicleStatus"]) ~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'vehicleStatus' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 135, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 474, in update_vehicle_with_cached_state state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 169, in _get_vehicle_status status = dict(response["vehicleStatus"]) ~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'vehicleStatus'
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 115, in check_and_force_update_vehicles
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 474, in update_vehicle_with_cached_state
    state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 169, in _get_vehicle_status
    status = dict(response["vehicleStatus"])
                  ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'vehicleStatus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 135, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 474, in update_vehicle_with_cached_state
    state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 169, in _get_vehicle_status
    status = dict(response["vehicleStatus"])
                  ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'vehicleStatus'
Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md


**To Reproduce**
Reload integration
![Hyundai_Integration](https://github.com/user-attachments/assets/6fbe3fb6-e38c-4147-b89b-6f1ab61c95f8)


**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
I'm a dummy so if I have not provided the correct logs please provide the steps. I have added the debug aspect in my configuration.yaml and restarted HA. I went to system > logs and pasted those logs.....

**Comment by cdnninja** [comment]
I can't remember the button but at the bottom of the log section a button exists to load full logs.  Will need some of that.

**Comment by steps56** [comment]
Do you have tried to delete the integration, reload it an start new setup?
I always get at the setup the configuration asking for the Bluelink name, pw AND at 3. row the 4 digits pin for canada/US.
I set it at my setup too, despite I am located at Europe.
Doesn't hurt anything, but might be your problem not setting it beingvlocated in the US, isn't it ?

**Comment by LiveForToday** [comment]
Ok I worked this out. I was scrubbing the logs and noticed the 502 message on my old vehicle. I recently got a new vehicle from Hyundai and returned the old one on lease. I had previously, 2 days after I got the new vehicle tried to remove the old vehicle from owners.hyundaiusa.com but kept getting an error. Granted I was not seeing an error and could see both vehicles in the integration. Well I went in today to owners.hyundaiusa.com after seeing the 502 error and "removed" the vehicle from there. I reloaded the integration and voila it is now working. So in the end, if you get rid of a vehicle. Give it 3 to 4 days for them to get it out of the system or when bluelink shows it has no subscription ( this is what I noticed this morning ) and then delete the vehicle from the owners website. Reload your integration and you should be good.

**Comment by LiveForToday** [comment]
> Good find. Yes if native app isn't working for any vehicle listed neither will the integration.

Lesson learned for sure and thanks for confirming.
