### ISSUE TITLE
Zwei oder mehrere Ladevorgänge zusammenführen - collate user selected seperate charging events()

### ISSUE THREAD

**Issue by prinzartus** [Hyundai-Kia-Connect/kia_uvo#935]
If charging events are interrrupted (by any means), it would be nice to be able to select - let's say three charging events - and collate them to a single charging event on the charging event screen. The "energie charged" and cost, duration to be summed up and the averages to be recalculated accordingly, just as if it was one uninterrupted charging event.

Maybe just during runtime only, while keeping the separate charging events in the db.

**Comment by cdnninja** [comment]
I don't think simple to due and is more of a home assistant request than kia_uvo.  Closing as not planned.
