### ISSUE TITLE
EV Mileage Range

### ISSUE THREAD

**Issue by sbukiet** [Hyundai-Kia-Connect/kia_uvo#936]
Lowest graph is 50 miles. How do I show down to 0?

**Comment by cdnninja** [comment]
I'm lost.  Does the car show 0 range but not showing as such?

**Comment by sbukiet** [comment]
Correct, the cars milage is below the 50 miles but the graph will cap at the 50 line. See image
<img width="397" alt="EV9_Range" src="https://github.com/user-attachments/assets/03e7f6dc-bcbe-41c6-8c28-80542d1b8533">

**Comment by cdnninja** [comment]
Can you screenshot the value on the sensor showing less than 50?
