### ISSUE TITLE
I can't start climate control on my Kia Niro 2021 EV 

### ISSUE THREAD

**Issue by legastm** [Hyundai-Kia-Connect/kia_uvo#938]
For my EU Kia E-Niro 2021 the remote off the climate control is not available, I can just read it's status.
With the phone app I can control It.
I don't found parameters in the HA integration to activate it.
Thank for your help !
![Screenshot_20240926_180812](https://github.com/user-attachments/assets/0e479c83-c1fb-4de0-ad80-f86bdf409ab7)

**Comment by cdnninja** [comment]
Action call in developers menu.

**Comment by legastm** [comment]
Perfect ! Thanks a lot !
I've made a button with the action start climate control !
