### ISSUE TITLE
When installing Integration: Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by vavallee** [Hyundai-Kia-Connect/kia_uvo#951]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada, Hyundai Ioniq 5

**Version of the integration**
v2.27.2

**Describe the bug**
After installing the HACS plugin and restarting I get this error and it will not move forward with the installation.

Error

Config flow could not be loaded: {"message":"Invalid handler specified"}

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
Nothing in logs, or I cannot find them.

**To Reproduce**
Install HA, HACS, Kia Ovo

**Expected behavior**
In installs correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/d06268d8-237f-4907-9bf0-bf205d13c033)

**Additional context**

**Comment by cdnninja** [comment]
Could you try 2.27.1 and let me know if same issue?

**Comment by vavallee** [comment]
Yes, just tried it, has the same error.

**Comment by cdnninja** [comment]
Please enable debug logs and provide that.

**Comment by vavallee** [comment]
All I get is
: " 2024-10-22 20:08:10.988 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration kia_uvo: No module named 'hyundai_kia_connect_api'"

**Comment by cdnninja** [comment]
What are you hosting this on? Linux server docker image by any chance?

**Comment by vavallee** [comment]
> What are you hosting this on? Linux server docker image by any chance?

Yes, Kuberneted with Docker image homeassistant/home-assistant:2024.10.0

**Comment by vavallee** [comment]
So when I exec-ed into the pod and installed the python package, it seemed to install ok. Just testing it now.

``` pip install hyundai-kia-connect-api

**Comment by vavallee** [comment]
sadly doesn't survive restart though.

**Comment by cdnninja** [comment]
You shouldn't need to install by hand.  This will break future releases.    Manifest.json instructs the install.   

A bug existed in the Linux server image that caused this for any integration.  Let me try find the link.

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/945

If not on the image referenced I encourage you to open an issue on the docker image page.  

I know home assistant changed install method for dependencies in that release as well.

**Comment by cdnninja** [comment]
I think this is the issue you are facing 

https://github.com/home-assistant/core/issues/128214

**Comment by vavallee** [comment]
> I think this is the issue you are facing
> 
> [home-assistant/core#128214](https://github.com/home-assistant/core/issues/128214)

Thanks, though I am not sure what exactly needs to be done to the HA image?

**Comment by mbudnek** [comment]
I just ran into this same issue, and the problem doesn't seem to be related to home-assistant/core#128214.  For me, HA is successfully installing the `hyundai_kia_connect_api` package, but it installs it to /config/deps, and for whatever reason it still doesn't get found when I try to configure the integration:

```
2024-10-27 02:52:33.249 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of hyundai_kia_connect_api==3.23.8
2024-10-27 02:52:33.249 DEBUG (SyncWorker_2) [homeassistant.util.package] Running uv pip command: args=['uv', 'pip', 'install', '--quiet', 'hyundai_kia_connect_api==3.23.8', '--index-strategy', 'unsafe-first-match', '--upgrade', '--constraint', '/usr/src/homeassistant/homeassistant/package_constraints.txt', '--target', '/config/deps']
2024-10-27 02:52:34.591 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration kia_uvo: No module named 'hyundai_kia_connect_api'
```

And indeed, the package is there in /config/deps:
```
# ls /config/deps
beautifulsoup4-4.12.3.dist-info           idna-3.10.dist-info
bin                                       python_dateutil-2.9.0.post0.dist-info
bs4                                       pytz
certifi                                   pytz-2024.2.dist-info
certifi-2024.8.30.dist-info               requests
charset_normalizer                        requests-2.32.3.dist-info
charset_normalizer-3.2.0.dist-info        six-1.16.0.dist-info
curlify-2.2.1.dist-info                   six.py
curlify.py                                soupsieve
dateutil                                  soupsieve-2.6.dist-info
hyundai_kia_connect_api                   urllib3
hyundai_kia_connect_api-3.23.8.dist-info  urllib3-1.26.20.dist-info
idna
```

**Comment by cdnninja** [comment]
I encourage you to report this to the container owners since this isn't caused by Kia uvo.

**Comment by vavallee** [comment]
Latest image releaase 2024.10.4 solves the issue for me
