### ISSUE TITLE
Location never shows "home" anymore.

### ISSUE THREAD

**Issue by Ricks88** [Hyundai-Kia-Connect/kia_uvo#964]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**

**Version of the integration**
2.28.1

**Describe the bug**
Location reports "away/not_home" when home.

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**
Show that the car is "home".

**Additional context**
As of a few weeks (a reinstall of HA and all addons) the location sensors always shows "not_home" even if the geocoded_location reports my Home adress and the car is in the HA Home zones (on map).

**Comment by cdnninja** [comment]
We don't set home vs home.   To confirm the physical location also shows the gps of "home"?  Geocode location isn't used for home away.  

If gps location is correct this is home assistant config.   Unrelated to Kia uvo.
