### ISSUE TITLE
It would be great if turning on/off climate would work again in EU for cars newer than 2023.

### ISSUE THREAD

**Issue by st3ve0** [Hyundai-Kia-Connect/kia_uvo#967]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Include the logs of the end point from Data in HA if this is a sensor**

**Describe alternatives you've considered**

**Additional context**

**Comment by teodorch85** [comment]
It works for my Ioniq 5 2024.
I tested today.
