### ISSUE TITLE
EU >2023 climate on/off

### ISSUE THREAD

**Issue by st3ve0** [Hyundai-Kia-Connect/kia_uvo#968]
It would be great, if you could turn on/off climate with newer Hyundai models. As from the table, it worked/is working for older models in the EU?

**Comment by cdnninja** [comment]
To my knowledge works on newer too.

**Comment by st3ve0** [comment]
There it says no, and I don't habe a button or something to start it. Only shows if its on or off, but no toggle or something.

Service	           EU	|EU(>2023)
start stop climate	✔	| ✖

**Comment by cdnninja** [comment]
It's an action / service call from developer menu.  If it works please report back and we can change docs.

**Comment by gaillal** [comment]
> It's an action / service call from developer menu. If it works please report back and we can change docs.

Where can I find step by step instruction to call such a service?  Thanks.

**Comment by st3ve0** [comment]
Hi,
it is working.
I was able to start it with an automation. THX!

@gaillal for the action, you have to scroll down all to the end and choose "other action", then you can choose "Hyundai /Kia Connect". There are more things you can trigger with this automation like starting/stopping the climate process, choose the temperature and more.

**Comment by cdnninja** [comment]
It can also be accessed via the developer menu.

**Comment by st3ve0** [comment]
Sorry, I'm not familiar with the developer menu? Where do I access it? I have everything in german so i don't really know where to go...

**Comment by st3ve0** [comment]
ah yes I found it. you can change it to on and it works there too.

**Comment by Strixx76** [comment]
It works on my Ioniq 5 2024

**Comment by gaillal** [comment]
Can one of you expand on how that function is accessed?  Thanks!

**Comment by st3ve0** [comment]
sure.
so I use it in an automation. it is an Action where in the gui you can click on add Action, then scroll down to the end an click "other Actions",in the next selection you search for the Plugin "Hyundai/ Kia Connect" and click on it. In there, you can select what you want, like open the car, configure the Climate or start/stop the charging.

I hope this helps you. If you want other Details, just ask :)

**Comment by gaillal** [comment]
Great! Thank you so much! I did not figure out to use the “other action”!
