### ISSUE TITLE
Battery percentage data

### ISSUE THREAD

**Issue by amityaaron** [Hyundai-Kia-Connect/kia_uvo#978]
sorry for creating an issue for probably a non issue.

How does the integration calculate the % battery remaining?
this info isnt in the kia connect app, it just has a status thats either good or warning?

iv been having some battery issues and was relying on the % remaining but im not sure how accurate this reading is.

iv been using a multimeter to also check the voltage on the battery but theres some inconsistencies when comparing to the % remaining value.

**Comment by fuatakgun** [comment]
no need to sorry. for some cars, this info is coming as response of API request, but not visible on UI. we are just showing the incoming data as a sensor, we do not compute it.

**Comment by amityaaron** [comment]
I see, thanks for the info! I thought that was the case.
