### ISSUE TITLE
Not working: Enable Geolocation Entity using OpenStreetMap

### ISSUE THREAD

**Issue by mikesalz** [Hyundai-Kia-Connect/kia_uvo#991]
**Region and Brand of car**
USA / Genesis 

**Version of the integration**
2.31.0

**Describe the bug**
I checked the option for "Enable Geolocation Entity using OpenStreetMap" but no entity is created.  I can see the Latitude and Longitude under Location.  But no address or geolocation entity is created.

**Comment by cdnninja** [comment]
Does restarting the integration fix it?

**Comment by mikesalz** [comment]
Thanks for the quick response!  When you say restarting, I am assuming you mean reloading?
![image](https://github.com/user-attachments/assets/4ee82f35-19e1-47d9-8786-9a1201ee552f)

Unfortunately that does not help.

**Comment by mikesalz** [comment]
I was going to upload my debug log, but it is loaded with personal information.  I did see this at the bottom, though:

> 2024-12-19 09:06:20.494 DEBUG (SyncWorker_40) [hyundai_kia_connect_api.ApiImpl] hyundai_kia_connect_api - Running update geocode location with value: https://nominatim.openstreetmap.org/reverse?lat=xxxx&lon=-xxxx&format=json&addressdetails=1&zoom=18
> 2024-12-19 09:06:21.055 DEBUG (SyncWorker_40) [hyundai_kia_connect_api.ApiImpl] hyundai_kia_connect_api - geocode location raw response: <Response [403]>
> 2024-12-19 09:06:21.056 DEBUG (SyncWorker_40) [hyundai_kia_connect_api.ApiImpl] hyundai_kia_connect_api - failed to decode json for geocode location
> 2024-12-19 09:06:21.060 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 122.450 seconds (success: True)
>

**Comment by mikesalz** [comment]
Hi @cdnninja - just wondering if you have any further thoughts here? Is there anything I can do to help test?

**Comment by cdnninja** [comment]
Do you have the use email for geocode enabled?

**Comment by mikesalz** [comment]
Ok, that helped. Now it is showing the entity. However, it is not correct. It has the right street address and street name, but the wrong zip code and city.

**Comment by cdnninja** [comment]
Would need to take that up with the open street service.
